# 1. Importing Packages

In [1]:
import pandas as pd
import numpy as np
import pymysql as ps
import requests as rq
import yfinance as yf
from sqlalchemy import create_engine as ce

# 2. Collecting Data

## 2.1. Cryptocurrencies

In [2]:
data_crypto = []
for i in range(1,6):
    url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page={i}&sparkline=False"
    response = rq.get(url)
    if response.status_code == 200:
        data_crypto = data_crypto + response.json()
    else:
        print(f"Failed on {i} page")

Failed on 4 page
Failed on 5 page

In [3]:
data_crypto

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 6414985,
  'market_cap': 128311563585094,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 128311563585094,
  'total_volume': 4177318101927,
  'high_24h': 6566049,
  'low_24h': 6352278,
  'price_change_24h': -419.86707268375903,
  'price_change_percentage_24h': -0.00654,
  'market_cap_change_24h': 22371034663,
  'market_cap_change_percentage_24h': 0.01744,
  'circulating_supply': 20001087.0,
  'total_supply': 20001087.0,
  'max_supply': 21000000.0,
  'ath': 11187013,
  'ath_change_percentage': -42.65686,
  'ath_date': '2025-10-06T18:57:42.558Z',
  'atl': 3993.42,
  'atl_change_percentage': 160538.89264,
  'atl_date': '2013-07-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:52.848Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 187247,
  'market_cap': 22600030164638,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 22600030164638,
  'total_volume': 1773459242925,
  'high_24h': 191971,
  'low_24h': 184870,
  'price_change_24h': 1644.44,
  'price_change_percentage_24h': 0.886,
  'market_cap_change_24h': 204807891261,
  'market_cap_change_percentage_24h': 0.91452,
  'circulating_supply': 120691977.447831,
  'total_supply': 120691977.447831,
  'max_supply': None,
  'ath': 431946,
  'ath_change_percentage': -56.65024,
  'ath_date': '2025-08-24T19:21:03.333Z',
  'atl': 28.13,
  'atl_change_percentage': 665520.78818,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 37.995420434107444,
   'currency': 'btc',
   'percentage': 3799.542043410744},
  'last_updated': '2026-03-12T06:25:52.807Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 92.36,
  'market_cap': 16989644268742,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 17494544116311,
  'total_volume': 6460807571040,
  'high_24h': 92.37,
  'low_24h': 91.86,
  'price_change_24h': 0.472708,
  'price_change_percentage_24h': 0.51447,
  'market_cap_change_24h': 87914991599,
  'market_cap_change_percentage_24h': 0.52015,
  'circulating_supply': 183959901909.3361,
  'total_supply': 189426839589.9362,
  'max_supply': None,
  'ath': 105.52,
  'ath_change_percentage': -12.47647,
  'ath_date': '2025-01-25T16:51:57.989Z',
  'atl': 36.86,
  'atl_change_percentage': 150.55546,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T06:24:43.928Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 59550,
  'market_cap': 8120312917655,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 8120312917655,
  'total_volume': 90807512182,
  'high_24h': 60432,
  'low_24h': 58567,
  'price_change_24h': 670.15,
  'price_change_percentage_24h': 1.13816,
  'market_cap_change_24h': 86187551007,
  'market_cap_change_percentage_24h': 1.07277,
  'circulating_supply': 136358220.72,
  'total_supply': 136358220.72,
  'max_supply': 200000000.0,
  'ath': 121422,
  'ath_change_percentage': -50.95607,
  'ath_date': '2025-10-13T08:41:24.131Z',
  'atl': 2.58,
  'atl_change_percentage': 2303813.29867,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:52.628Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 126.51,
  'market_cap': 7745776098884,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 12648934772451,
  'total_volume': 215632633894,
  'high_24h': 129.53,
  'low_24h': 126.29,
  'price_change_24h': -0.22952498829275214,
  'price_change_percentage_24h': -0.1811,
  'market_cap_change_24h': -15372781430.84082,
  'market_cap_change_percentage_24h': -0.19807,
  'circulating_supply': 61227832454.0,
  'total_supply': 99985701766.0,
  'max_supply': 100000000000.0,
  'ath': 313.99,
  'ath_change_percentage': -59.70933,
  'ath_date': '2025-07-21T15:02:00.541Z',
  'atl': 0.159343,
  'atl_change_percentage': 79293.22639,
  'atl_date': '2013-08-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T06:24:43.538Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 92.35,
  'market_cap': 7279585696347,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 7280055914268,
  'total_volume': 1062044784517,
  'high_24h': 92.36,
  'low_24h': 91.86,
  'price_change_24h': 0.436677,
  'price_change_percentage_24h': 0.47509,
  'market_cap_change_24h': 50522228647,
  'market_cap_change_percentage_24h': 0.69888,
  'circulating_supply': 78821762211.89995,
  'total_supply': 78826853628.73671,
  'max_supply': None,
  'ath': 92.36,
  'ath_change_percentage': -0.01411,
  'ath_date': '2026-03-12T05:01:01.830Z',
  'atl': 65.31,
  'atl_change_percentage': 41.40285,
  'atl_date': '2021-05-19T13:14:05.611Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:30.522Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 7861.77,
  'market_cap': 4488668416940,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 4488668516602,
  'total_volume': 361030047457,
  'high_24h': 8100.56,
  'low_24h': 7774.83,
  'price_change_24h': -36.98370197105578,
  'price_change_percentage_24h': -0.46822,
  'market_cap_change_24h': -11595217194.024414,
  'market_cap_change_percentage_24h': -0.25766,
  'circulating_supply': 571113704.331899,
  'total_supply': 571113717.0123715,
  'max_supply': None,
  'ath': 25396,
  'ath_change_percentage': -69.04365,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 38.03,
  'atl_change_percentage': 20574.89207,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:39.547Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193',
  'current_price': 26.77,
  'market_cap': 2536564895079,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 2536588154704,
  'total_volume': 45795326786,
  'high_24h': 26.92,
  'low_24h': 26.39,
  'price_change_24h': 0.342971,
  'price_change_percentage_24h': 1.29769,
  'market_cap_change_24h': 31655799656,
  'market_cap_change_percentage_24h': 1.26375,
  'circulating_supply': 94746059267.7016,
  'total_supply': 94746928063.83789,
  'max_supply': None,
  'ath': 36.53,
  'ath_change_percentage': -26.70265,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.117589,
  'atl_change_percentage': 22667.5517,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 151.59081706559246,
   'currency': 'usd',
   'percentage': 15159.081706559247},
  'last_updated': '2026-03-12T06:25:47.529Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 94.84,
  'market_cap': 1494487730429,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 1494487730429,
  'total_volume': 1808823669,
  'high_24h': 95.54,
  'low_24h': 94.67,
  'price_change_24h': -0.37442661173548686,
  'price_change_percentage_24h': -0.39323,
  'market_cap_change_24h': -2676593318.6467285,
  'market_cap_change_percentage_24h': -0.17878,
  'circulating_supply': 15757493780.407,
  'total_supply': 15757493780.407,
  'max_supply': None,
  'ath': 96.67,
  'ath_change_percentage': -1.88544,
  'ath_date': '2026-03-09T17:10:26.081Z',
  'atl': 13.78,
  'atl_change_percentage': 588.02283,
  'atl_date': '2025-10-31T14:57:19.271Z',
  'roi': None,
  'last_updated': '2026-03-12T05:00:14.577Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 8.49,
  'market_cap': 1302187673501,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 1435584926130,
  'total_volume': 102401258556,
  'high_24h': 8.71,
  'low_24h': 8.43,
  'price_change_24h': 0.04955876,
  'price_change_percentage_24h': 0.58714,
  'market_cap_change_24h': 6980229817,
  'market_cap_change_percentage_24h': 0.53893,
  'circulating_supply': 153374576383.7052,
  'total_supply': 169086403126.5791,
  'max_supply': None,
  'ath': 53.62,
  'ath_change_percentage': -84.16523,
  'ath_date': '2021-05-08T05:08:23.458Z',
  'atl': 0.00552883,
  'atl_change_percentage': 153463.0365,
  'atl_date': '2015-05-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.622Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 5065.79,
  'market_cap': 1081285034976,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 1620867958531,
  'total_volume': 5309450605,
  'high_24h': 5182.72,
  'low_24h': 5044.55,
  'price_change_24h': -13.707617368931096,
  'price_change_percentage_24h': -0.26986,
  'market_cap_change_24h': -3087654258.9624023,
  'market_cap_change_percentage_24h': -0.28474,
  'circulating_supply': 213418274.0,
  'total_supply': 319918274.0,
  'max_supply': 400000000.0,
  'ath': 5758.63,
  'ath_change_percentage': -12.02873,
  'ath_date': '2025-12-10T20:16:13.582Z',
  'atl': 245.71,
  'atl_change_percentage': 1961.7762,
  'atl_date': '2022-09-21T23:38:03.675Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.309Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 92.34,
  'market_cap': 1033983571240,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 1033983571240,
  'total_volume': 1562191647,
  'high_24h': 92.36,
  'low_24h': 91.9,
  'price_change_24h': 0.439922,
  'price_change_percentage_24h': 0.47872,
  'market_cap_change_24h': 9752482453,
  'market_cap_change_percentage_24h': 0.95218,
  'circulating_supply': 11196885490.13781,
  'total_supply': 11196885490.13781,
  'max_supply': None,
  'ath': 92.43,
  'ath_change_percentage': -0.09292,
  'ath_date': '2026-03-09T05:21:13.011Z',
  'atl': 79.67,
  'atl_change_percentage': 15.90949,
  'atl_date': '2024-10-03T13:19:28.826Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.290Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 23.93,
  'market_cap': 881274188453,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 1076664150583,
  'total_volume': 41353781757,
  'high_24h': 24.55,
  'low_24h': 23.66,
  'price_change_24h': 0.109989,
  'price_change_percentage_24h': 0.46183,
  'market_cap_change_24h': 3982636536,
  'market_cap_change_percentage_24h': 0.45397,
  'circulating_supply': 36833527390.06435,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 225.26,
  'ath_change_percentage': -89.37861,
  'ath_date': '2021-09-02T06:00:10.474Z',
  'atl': 1.38,
  'atl_change_percentage': 1639.54503,
  'atl_date': '2017-11-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.730Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 41915,
  'market_cap': 838558411846,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 838558673815,
  'total_volume': 18682251488,
  'high_24h': 42351,
  'low_24h': 41186,
  'price_change_24h': 412.03,
  'price_change_percentage_24h': 0.99278,
  'market_cap_change_24h': 7708177923,
  'market_cap_change_percentage_24h': 0.92775,
  'circulating_supply': 20006178.02165078,
  'total_supply': 20006184.27165078,
  'max_supply': 21000000.0,
  'ath': 242198,
  'ath_change_percentage': -82.69391,
  'ath_date': '2017-12-20T00:00:00.000Z',
  'atl': 5536.54,
  'atl_change_percentage': 657.06139,
  'atl_date': '2018-12-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.435Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 3437.54,
  'market_cap': 818957901609,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 3305832477015,
  'total_volume': 40788641662,
  'high_24h': 3447.47,
  'low_24h': 3150.31,
  'price_change_24h': 260.07,
  'price_change_percentage_24h': 8.18474,
  'market_cap_change_24h': 62570179013,
  'market_cap_change_percentage_24h': 8.27224,
  'circulating_supply': 238385315.9541414,
  'total_supply': 962274028.9541414,
  'max_supply': 1000000000.0,
  'ath': 5213.52,
  'ath_change_percentage': -34.065,
  'ath_date': '2025-09-18T03:30:30.650Z',
  'atl': 321.88,
  'atl_change_percentage': 967.95839,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.358Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 837.94,
  'market_cap': 771916353266,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 825628154452,
  'total_volume': 133240687,
  'high_24h': 851.77,
  'low_24h': 835.47,
  'price_change_24h': -10.412102049270857,
  'price_change_percentage_24h': -1.22734,
  'market_cap_change_24h': -9434036242.497925,
  'market_cap_change_percentage_24h': -1.2074,
  'circulating_supply': 921144077.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 888.26,
  'ath_change_percentage': -5.66354,
  'ath_date': '2025-12-01T06:16:28.002Z',
  'atl': 56.97,
  'atl_change_percentage': 1370.77087,
  'atl_date': '2019-12-24T15:14:35.376Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.285Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 32646,
  'market_cap': 602211914871,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 602211914871,
  'total_volume': 8399642452,
  'high_24h': 33108,
  'low_24h': 32023,
  'price_change_24h': -217.4928753522181,
  'price_change_percentage_24h': -0.66181,
  'market_cap_change_24h': -4063448854.7061768,
  'market_cap_change_percentage_24h': -0.67023,
  'circulating_supply': 18446744.07370955,
  'total_supply': 18446744.07370955,
  'max_supply': None,
  'ath': 72026,
  'ath_change_percentage': -54.67461,
  'ath_date': '2026-01-14T19:34:07.049Z',
  'atl': 13.57,
  'atl_change_percentage': 240459.32548,
  'atl_date': '2015-01-14T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.422Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 821.51,
  'market_cap': 581712102145,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 821511264536,
  'total_volume': 28788349952,
  'high_24h': 841.55,
  'low_24h': 816.84,
  'price_change_24h': 1.75,
  'price_change_percentage_24h': 0.21338,
  'market_cap_change_24h': 1238597682,
  'market_cap_change_percentage_24h': 0.21338,
  'circulating_supply': 708099970.4525867,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 3862.15,
  'ath_change_percentage': -78.72919,
  'ath_date': '2021-05-10T00:13:57.214Z',
  'atl': 9.55,
  'atl_change_percentage': 8505.21789,
  'atl_date': '2017-11-29T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.784Z'},
 {'id': 'ethena-usde',
  'symbol': 'usde',
  'name': 'Ethena USDe',
  'image': 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059',
  'current_price': 92.29,
  'market_cap': 546093457365,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 546093457365,
  'total_volume': 6037819755,
  'high_24h': 92.33,
  'low_24h': 91.81,
  'price_change_24h': 0.411882,
  'price_change_percentage_24h': 0.4483,
  'market_cap_change_24h': 1863347817,
  'market_cap_change_percentage_24h': 0.34238,
  'circulating_supply': 5916596181.308628,
  'total_supply': 5916596181.308628,
  'max_supply': None,
  'ath': 92.91,
  'ath_change_percentage': -0.67551,
  'ath_date': '2025-12-09T17:10:12.652Z',
  'atl': 78.05,
  'atl_change_percentage': 18.2464,
  'atl_date': '2024-10-04T07:57:15.809Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.486Z'},
 {'id': 'canton-network',
  'symbol': 'cc',
  'name': 'Canton',
  'image': 'https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299',
  'current_price': 13.87,
  'market_cap': 527233979175,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 527233979175,
  'total_volume': 23902444001,
  'high_24h': 14.29,
  'low_24h': 13.48,
  'price_change_24h': 0.256322,
  'price_change_percentage_24h': 1.88316,
  'market_cap_change_24h': 9921212801,
  'market_cap_change_percentage_24h': 1.91784,
  'circulating_supply': 38014461318.39068,
  'total_supply': 38014461318.39068,
  'max_supply': None,
  'ath': 17.72,
  'ath_change_percentage': -21.75055,
  'ath_date': '2026-01-31T16:41:41.560Z',
  'atl': 5.31,
  'atl_change_percentage': 161.2302,
  'atl_date': '2025-12-06T10:32:09.784Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.350Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 14.48,
  'market_cap': 477941966703,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 724093378682,
  'total_volume': 8277621036,
  'high_24h': 14.87,
  'low_24h': 14.32,
  'price_change_24h': 0.105587,
  'price_change_percentage_24h': 0.73448,
  'market_cap_change_24h': 3494807262,
  'market_cap_change_percentage_24h': 0.73661,
  'circulating_supply': 33003964772.21671,
  'total_supply': 50001786883.65895,
  'max_supply': None,
  'ath': 55.54,
  'ath_change_percentage': -73.93575,
  'ath_date': '2018-01-03T00:00:00.000Z',
  'atl': 0.02966141,
  'atl_change_percentage': 48706.15197,
  'atl_date': '2015-03-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.720Z'},
 {'id': 'usd1-wlfi',
  'symbol': 'usd1',
  'name': 'USD1',
  'image': 'https://coin-images.coingecko.com/coins/images/54977/large/USD1_1000x1000_transparent.png?1749297002',
  'current_price': 92.28,
  'market_cap': 425757151846,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 425757151846,
  'total_volume': 119469464034,
  'high_24h': 92.31,
  'low_24h': 91.81,
  'price_change_24h': 0.431049,
  'price_change_percentage_24h': 0.46929,
  'market_cap_change_24h': 2270360118,
  'market_cap_change_percentage_24h': 0.53611,
  'circulating_supply': 4613424583.988876,
  'total_supply': 4613424583.988876,
  'max_supply': None,
  'ath': 92.34,
  'ath_change_percentage': -0.06041,
  'ath_date': '2026-03-03T15:25:15.271Z',
  'atl': 83.75,
  'atl_change_percentage': 10.19392,
  'atl_date': '2025-05-02T03:46:49.689Z',
  'roi': None,
  'last_updated': '2026-03-12T06:25:47.905Z'},
 {'id': 'dai',
  'symbol': 'dai',
  'name': 'Dai',
  'image': 'https://coin-images.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996',
  'current_price': 92.33,
  'market_cap': 393942738319,
  'market_cap_rank': 23,
  'fully_diluted_valuation': 393942738319,
  'total_volume': 12737557093,
  'high_24h': 92.36,
  'low_24h': 91.85,
  'price_change_24h': 0.433001,
  'price_change_percentage_24h': 0.47116,

In [4]:
required_columns = ['id', 'symbol', 'name', 'current_price', 'market_cap','market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply', 'ath', 'atl', 'last_updated']
df_crypto = pd.DataFrame(data_crypto)
df_crypto = df_crypto[required_columns]

In [5]:
df_crypto.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,6414985.00,128311563585094,1,4.177318e+12,2.000109e+07,2.000109e+07,11187013.00,3993.420000,2026-03-12T06:25:52.848Z
1,ethereum,eth,Ethereum,187247.00,22600030164638,2,1.773459e+12,1.206920e+08,1.206920e+08,431946.00,28.130000,2026-03-12T06:25:52.807Z
2,tether,usdt,Tether,92.36,16989644268742,3,6.460808e+12,1.839599e+11,1.894268e+11,105.52,36.860000,2026-03-12T06:24:43.928Z
3,binancecoin,bnb,BNB,59550.00,8120312917655,4,9.080751e+10,1.363582e+08,1.363582e+08,121422.00,2.580000,2026-03-12T06:25:52.628Z
4,ripple,xrp,XRP,126.51,7745776098884,5,2.156326e+11,6.122783e+10,9.998570e+10,313.99,0.159343,2026-03-12T06:24:43.538Z

## 2.2 Historical prices - Top 3 Cryptocurrencies

### 2.2.1 Bitcoin

In [6]:
coin_id = "bitcoin"
top3_crypto = []
url = "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=inr&days=365"
response = rq.get(url)

if response.status_code == 200:
    top3_crypto_bitcoin = response.json()

In [7]:
top3_crypto_bitcoin

{'prices': [[1741824000000, 7311397.167011021],
  [1741910400000, 7049331.751158462],
  [1741996800000, 7301205.756783538],
  [1742083200000, 7337203.4861049205],
  [1742169600000, 7182714.546311197],
  [1742256000000, 7307625.213417549],
  [1742342400000, 7166130.900539224],
  [1742428800000, 7495414.341859128],
  [1742515200000, 7275140.94449613],
  [1742601600000, 7224000.906005809],
  [1742688000000, 7205763.671408613],
  [1742774400000, 7377568.408827406],
  [1742860800000, 7471026.999919416],
  [1742947200000, 7490943.665690553],
  [1743033600000, 7448415.462567322],
  [1743120000000, 7474953.075439318],
  [1743206400000, 7216289.858225705],
  [1743292800000, 7072289.607125187],
  [1743379200000, 7044678.366106417],
  [1743465600000, 7049110.1215911815],
  [1743552000000, 7295181.762562074],
  [1743638400000, 7072204.244187081],
  [1743724800000, 7092361.1660758825],
  [1743811200000, 7177434.935222951],
  [1743897600000, 7149914.289024058],
  [1743984000000, 6689389.08502666],
  [1744070400000, 6810911.664670934],
  [1744156800000, 6597493.475585312],
  [1744243200000, 7122745.761241968],
  [1744329600000, 6866025.560636041],
  [1744416000000, 7182775.418149425],
  [1744502400000, 7333947.924555619],
  [1744588800000, 7187425.846627208],
  [1744675200000, 7271599.950976666],
  [1744761600000, 7171572.949306771],
  [1744848000000, 7201187.29755112],
  [1744934400000, 7251703.328254263],
  [1745020800000, 7209254.173849113],
  [1745107200000, 7268417.49030321],
  [1745193600000, 7263849.726468839],
  [1745280000000, 7447341.987486609],
  [1745366400000, 7975735.892697773],
  [1745452800000, 8003280.21321444],
  [1745539200000, 8000169.783417303],
  [1745625600000, 8092178.475391482],
  [1745712000000, 8081159.94608841],
  [1745798400000, 8009924.38113424],
  [1745884800000, 8092853.390805625],
  [1745971200000, 8027696.597798843],
  [1746057600000, 7968688.759781316],
  [1746144000000, 8167058.515487802],
  [1746230400000, 8196935.158997864],
  [1746316800000, 8118000.316161074],
  [1746403200000, 7973099.086450076],
  [1746489600000, 7980688.008703099],
  [1746576000000, 8207545.052481962],
  [1746662400000, 8229539.783984127],
  [1746748800000, 8868161.595114123],
  [1746835200000, 8794022.755272726],
  [1746921600000, 8936515.44901635],
  [1747008000000, 8882429.185761888],
  [1747094400000, 8739740.641206343],
  [1747180800000, 8860925.91388854],
  [1747267200000, 8854656.259617174],
  [1747353600000, 8861418.050018335],
  [1747440000000, 8862661.820151662],
  [1747526400000, 8833249.416670207],
  [1747612800000, 9065676.354329923],
  [1747699200000, 9017978.28123392],
  [1747785600000, 9134061.037906067],
  [1747872000000, 9387459.456660772],
  [1747958400000, 9591418.421810476],
  [1748044800000, 9121570.655984685],
  [1748131200000, 9173866.493436038],
  [1748217600000, 9274975.732278159],
  [1748304000000, 9314436.685236426],
  [1748390400000, 9310175.102671716],
  [1748476800000, 9208280.990679564],
  [1748563200000, 9026592.666677358],
  [1748649600000, 8900073.972215421],
  [1748736000000, 8957968.682594351],
  [1748822400000, 9040802.274014382],
  [1748908800000, 9038740.617012177],
  [1748995200000, 9036688.899610182],
  [1749081600000, 9003749.459208991],
  [1749168000000, 8729536.730077919],
  [1749254400000, 8957197.574287502],
  [1749340800000, 9066295.741750069],
  [1749427200000, 9066867.46885247],
  [1749513600000, 9455619.179043707],
  [1749600000000, 9440056.689266069],
  [1749686400000, 9288882.88186932],
  [1749772800000, 9081227.025134273],
  [1749859200000, 9132702.543985052],
  [1749945600000, 9084246.101299008],
  [1750032000000, 9090411.27477335],
  [1750118400000, 9208980.453923177],
  [1750204800000, 9039952.955659283],
  [1750291200000, 9070436.848135183],
  [1750377600000, 9080584.318377115],
  [1750464000000, 8945088.576284403],
  [1750550400000, 8792883.07729243],
  [1750636800000, 8731873.284684414],
  [1750723200000, 9111429.945371069],
  [1750809600000, 9111165.38661966],
  [1750896000000, 9223086.808659252],
  [1750982400000, 9165684.099752242],
  [1751068800000, 9156217.740562832],
  [1751155200000, 9177823.305095606],
  [1751241600000, 9263092.465181679],
  [1751328000000, 9181709.414667957],
  [1751414400000, 9054321.250569785],
  [1751500800000, 9325640.339018358],
  [1751587200000, 9360532.463404836],
  [1751673600000, 9250500.062624797],
  [1751760000000, 9285248.177863376],
  [1751846400000, 9337523.923073687],
  [1751932800000, 9302203.177316865],
  [1752019200000, 9338122.035800587],
  [1752105600000, 9541743.483380785],
  [1752192000000, 9934947.612549465],
  [1752278400000, 10091339.413757524],
  [1752364800000, 10078287.164944079],
  [1752451200000, 10222853.345055208],
  [1752537600000, 10301939.218478084],
  [1752624000000, 10119542.204331392],
  [1752710400000, 10198739.393321177],
  [1752796800000, 10277885.47839658],
  [1752883200000, 10164069.670952292],
  [1752969600000, 10156547.547410768],
  [1753056000000, 10101549.352407157],
  [1753142400000, 10136533.758092493],
  [1753228800000, 10357349.26643955],
  [1753315200000, 10249425.74900696],
  [1753401600000, 10229427.683390176],
  [1753488000000, 10168020.4311719],
  [1753574400000, 10203795.311577797],
  [1753660800000, 10330494.375551593],
  [1753747200000, 10240072.841855934],
  [1753833600000, 10260715.669243045],
  [1753920000000, 10330510.927890545],
  [1754006400000, 10122552.718401065],
  [1754092800000, 9870309.502282668],
  [1754179200000, 9811174.470132805],
  [1754265600000, 9963363.104407016],
  [1754352000000, 10119947.866363142],
  [1754438400000, 10011721.5506572],
  [1754524800000, 10094655.435390146],
  [1754611200000, 10270107.263258504],
  [1754697600000, 10236807.855788205],
  [1754784000000, 10220759.730383817],
  [1754870400000, 10434491.300112702],
  [1754956800000, 10412275.449238887],
  [1755043200000, 10529495.638104321],
  [1755129600000, 10805439.78369676],
  [1755216000000, 10383230.847886154],
  [1755302400000, 10268856.947554458],
  [1755388800000, 10282983.838569582],
  [1755475200000, 10286533.101169772],
  [1755561600000, 10148644.242275473],
  [1755648000000, 9819786.419050021],
  [1755734400000, 9942066.543754837],
  [1755820800000, 9813063.27750558],
  [1755907200000, 10203164.21582744],
  [1755993600000, 10074416.19618185],
  [1756080000000, 9903221.35080575],
  [1756166400000, 9653212.189243559],
  [1756252800000, 9801777.668906499],
  [1756339200000, 9749130.25886824],
  [1756425600000, 9856302.06893481],
  [1756512000000, 9564432.013993934],
  [1756598400000, 9591794.692119835],
  [1756684800000, 9545191.818462053],
  [1756771200000, 9606486.0790093],
  [1756857600000, 9784574.242949013],
  [1756944000000, 9838796.609221794],
  [1757030400000, 9765163.284050079],
  [1757116800000, 9759026.631183332],
  [1757203200000, 9718962.630296323],
  [1757289600000, 9800346.003033817],
  [1757376000000, 9856054.84901548],
  [1757462400000, 9840553.151484529],
  [1757548800000, 10035954.764445597],
  [1757635200000, 10195205.098488238],
  [1757721600000, 10254357.380846838],
  [1757808000000, 10237593.3071353],
  [1757894400000, 10184894.127284445],
  [1757980800000, 10169238.650025213],
  [1758067200000, 10261685.530263504],
  [1758153600000, 10237752.888404036],
  [1758240000000, 10333070.25718556],
  [1758326400000, 10189201.725638028],
  [1758412800000, 10194461.688819751],
  [1758499200000, 10158260.693491202],
  [1758585600000, 9951646.271657305],
  [1758672000000, 9948492.512889242],
  [1758758400000, 10060469.351465985],
  [1758844800000, 9673068.167457229],
  [1758931200000, 9728251.057537576],
  [1759017600000, 9723915.967631772],
  [1759104000000, 9944472.608696878],
  [1759190400000, 10139763.924082505],
  [1759276800000, 10130020.723922314],
  [1759363200000, 10509252.859358784],
  [1759449600000, 10700725.995237181],
  [1759536000000, 10847910.013598107],
  [1759622400000, 10859533.642673422],
  [1759708800000, 10959365.064936124],
  [1759795200000, 11070472.246732509],
  [1759881600000, 10783920.730192943],
  [1759968000000, 10949945.97908964],
  [1760054400000, 10814774.599012492],
  [1760140800000, 10047260.111235712],
  [1760227200000, 9838358.210748602],
  [1760313600000, 10223942.881584922],
  [1760400000000, 10216224.051870666],
  [1760486400000, 10046351.075825775],
  [1760572800000, 9721344.884648668],
  [1760659200000, 9509774.024195194],
  [1760745600000, 9369768.130232994],
  [1760832000000, 9432476.848616607],
  [1760918400000, 9558930.877185136],
  [1761004800000, 9720308.914971137],
  [1761091200000, 9549158.301143315],
  [1761177600000, 9442499.946295625],
  [1761264000000, 9659976.397607893],
  [1761350400000, 9747832.72977752],
  [1761436800000, 9802501.15016422],
  [1761523200000, 10055171.794296525],
  [1761609600000, 10073474.454011032],
  [1761696000000, 9965129.220872145],
  [1761782400000, 9722166.86543983],
  [1761868800000, 9593893.17104472],
  [1761955200000, 9734748.91964181],
  [1762041600000, 9765788.362963019],
  [1762128000000, 9824421.072227614],
  [1762214400000, 9450928.858755054],
  [1762300800000, 9018317.599498693],
  [1762387200000, 9199126.082980732],
  [1762473600000, 8984607.813501872],
  [1762560000000, 9167651.236387476],
  [1762646400000, 9069592.039128657],
  [1762732800000, 9283589.00601575],
  [1762819200000, 9394913.182233905],
  [1762905600000, 9108594.696793688],
  [1762992000000, 8994239.327086337],
  [1763078400000, 8857694.85444411],
  [1763164800000, 8376936.116014769],
  [1763251200000, 8470582.749251666],
  [1763337600000, 8373085.239387692],
  [1763424000000, 8157780.455111292],
  [1763510400000, 8219844.429070548],
  [1763596800000, 8084502.70583037],
  [1763683200000, 7685198.360480496],
  [1763769600000, 7622398.708162882],
  [1763856000000, 7591078.566298594],
  [1763942400000, 7778520.446850556],
  [1764028800000, 7865475.253834086],
  [1764115200000, 7783791.323601658],
  [1764201600000, 8066930.863801428],
  [1764288000000, 8157156.351483771],
  [1764374400000, 8126220.637986011],
  [1764460800000, 8116488.479072998],
  [1764547200000, 8078246.317717989],
  [1764633600000, 7731939.31508293],
  [1764720000000, 8213485.439946512],
  [1764806400000, 8441734.894689914],
  [1764892800000, 8277612.193785475],
  [1764979200000, 8033337.656068311],
  [1765065600000, 8028324.929700683],
  [1765152000000, 8110183.521497487],
  [1765238400000, 8167418.75650716],
  [1765324800000, 8337407.11660591],
  [1765411200000, 8261440.281355997],
  [1765497600000, 8347818.307928058],
  [1765584000000, 8175319.49414227],
  [1765670400000, 8175924.735194205],
  [1765756800000, 7992348.231966222],
  [1765843200000, 7844409.288926788],
  [1765929600000, 7987315.985984798],
  [1766016000000, 7781471.915537124],
  [1766102400000, 7712879.171308659],
  [1766188800000, 7892110.371399885],
  [1766275200000, 7913974.621357582],
  [1766361600000, 7933999.65474005],
  [1766448000000, 7929162.75966298],
  [1766534400000, 7820620.968822208],
  [1766620800000, 7872946.774052088],
  [1766707200000, 7860175.221034703],
  [1766793600000, 7838865.798860937],
  [1766880000000, 7886342.002067149],
  [1766966400000, 7887770.596681177],
  [1767052800000, 7835388.056690424],
  [1767139200000, 7936951.056508718],
  [1767225600000, 7875103.91153735],
  [1767312000000, 7982611.090931888],
  [1767398400000, 8094664.567193232],
  [1767484800000, 8154755.980058913],
  [1767571200000, 8224912.970329631],
  [1767657600000, 8475311.204337161],
  [1767744000000, 8443838.294347357],
  [1767830400000, 8200790.873528976],
  [1767916800000, 8179932.125614385],
  [1768003200000, 8169727.593041189],
  [1768089600000, 8164051.8328820085],
  [1768176000000, 8196362.9552232],
  [1768262400000, 8214254.506811856],
  [1768348800000, 8600260.479528198],
  [1768435200000, 8754772.557780331],
  [1768521600000, 8637202.771129187],
  [1768608000000, 8665871.041073622],
  [1768694400000, 8641731.269593248],
  [1768780800000, 8504968.615885023],
  [1768867200000, 8414003.970645163],
  [1768953600000, 8046939.8302773405],
  [1769040000000, 8179241.969294843],
  [1769126400000, 8189307.776814618],
  [1769212800000, 8190756.883147298],
  [1769299200000, 8167427.829795334],
  [1769385600000, 7931480.8104405],
  [1769472000000, 8098992.121060789],
  [1769558400000, 8165356.488930265],
  [1769644800000, 8206661.924142179],
  [1769731200000, 7762053.970031044],
  [1769817600000, 7714332.820802952],
  [1769904000000, 7217787.461780625],
  [1769990400000, 7055170.4747747015],
  [1770076800000, 7124353.514366637],
  [1770163200000, 6839512.652076184],
  [1770249600000, 6617843.606631121],
  [1770336000000, 5676634.189757013],
  [1770422400000, 6389223.0613750955],
  [1770508800000, 6278047.808376017],
  [1770595200000, 6388983.809905373],
  [1770681600000, 6363124.007122537],
  [1770768000000, 6230645.199778009],
  [1770854400000, 6073656.888033923],
  [1770940800000, 5993963.2553228345],
  [1771027200000, 6234117.350281114],
  [1771113600000, 6317657.207954805],
  [1771200000000, 6222983.54818252],
  [1771286400000, 6255749.578602175],
  [1771372800000, 6116329.755578176],
  [1771459200000, 6033801.7653913135],
  [1771545600000, 6092367.347486159],
  [1771632000000, 6166730.671036533],
  [1771718400000, 6167421.5569663085],
  [1771804800000, 6132044.38390857],
  [1771891200000, 5877904.816486458],
  [1771977600000, 5825506.041087636],
  [1772064000000, 6179906.746479165],
  [1772150400000, 6139221.658943246],
  [1772236800000, 6000769.898243445],
  [1772323200000, 6102895.493287365],
  [1772409600000, 5984275.487394328],
  [1772496000000, 6305544.630558076],
  [1772582400000, 6286193.4883730775],
  [1772668800000, 6694568.0647264635],
  [1772755200000, 6505413.051213356],
  [1772841600000, 6265583.842492761],
  [1772928000000, 6184943.552139279],
  [1773014400000, 6071162.609842083],
  [1773100800000, 6319544.712079575],
  [1773187200000, 6427459.132593709],
  [1773273600000, 6476952.781587672],
  [1773296752000, 6414984.542032394]],
 'market_caps': [[1741824000000, 144904649435288.6],
  [1741910400000, 139813920027311.94],
  [1741996800000, 144832172272915.2],
  [1742083200000, 145556393063008.88],
  [1742169600000, 142477016504235.94],
  [1742256000000, 144960350656778.97],
  [1742342400000, 142195295862922.2],
  [1742428800000, 148635356385415.66],
  [1742515200000, 144391367721865.88],
  [1742601600000, 143324180216465.75],
  [1742688000000, 142972251116074.03],
  [1742774400000, 146369361522808.2],
  [1742860800000, 148236568994576.1],
  [1742947200000, 148531315670993.2],
  [1743033600000, 147738113790149.78],
  [1743120000000, 148250573414973.28],
  [1743206400000, 143127644099250.1],
  [1743292800000, 140340804500989.94],
  [1743379200000, 139770328164058.75],
  [1743465600000, 139683227029930.31],
  [1743552000000, 144692611411592.8],
  [1743638400000, 140315492944612.62],
  [1743724800000, 140931082892341.03],
  [1743811200000, 142452612689242.22],
  [1743897600000, 141638568405765.44],
  [1743984000000, 133026191892504.16],
  [1744070400000, 136030860146543.77],
  [1744156800000, 130952471210149.42],
  [1744243200000, 141431144678745.16],
  [1744329600000, 136293671033013.61],
  [1744416000000, 142543573292291.38],
  [1744502400000, 145604183184316.78],
  [1744588800000, 142622853806903.7],
  [1744675200000, 144345816768012.4],
  [1744761600000, 142370094856537.44],
  [1744848000000, 143029004221568.34],
  [1744934400000, 143976048009443.06],
  [1745020800000, 143134711526525.56],
  [1745107200000, 144305951874866.28],
  [1745193600000, 144213572928166.12],
  [1745280000000, 147811055811997.84],
  [1745366400000, 158412191601745.1],
  [1745452800000, 158915548781568.0],
  [1745539200000, 158882010025594.88],
  [1745625600000, 160704481873690.8],
  [1745712000000, 160449211873569.97],
  [1745798400000, 159053087736354.47],
  [1745884800000, 160703590988217.25],
  [1745971200000, 159335269302606.8],
  [1746057600000, 158243639764679.06],
  [1746144000000, 162184675927639.97],
  [1746230400000, 162765758571135.0],
  [1746316800000, 161212206683015.7],
  [1746403200000, 158302280917006.22],
  [1746489600000, 158547084714911.78],
  [1746576000000, 163011406532277.9],
  [1746662400000, 163454639004415.8],
  [1746748800000, 176189564081226.4],
  [1746835200000, 174667261488634.56],
  [1746921600000, 177407732339299.34],
  [1747008000000, 176433904354746.88],
  [1747094400000, 173674333299646.56],
  [1747180800000, 175999429237788.7],
  [1747267200000, 175888780326749.9],
  [1747353600000, 176029183872811.16],
  [1747440000000, 176106843788904.56],
  [1747526400000, 175472918502628.47],
  [1747612800000, 179969199355517.6],
  [1747699200000, 179155548290416.03],
  [1747785600000, 181486652295308.97],
  [1747872000000, 186509837960828.16],
  [1747958400000, 190410208940880.75],
  [1748044800000, 181347759081015.84],
  [1748131200000, 182278846776151.78],
  [1748217600000, 184292802432865.47],
  [1748304000000, 185054409080508.47],
  [1748390400000, 185024049829002.9],
  [1748476800000, 183019605072651.28],
  [1748563200000, 179374386620553.34],
  [1748649600000, 176855933911134.62],
  [1748736000000, 178022821809896.6],
  [1748822400000, 179702340560357.03],
  [1748908800000, 179629331590192.03],
  [1748995200000, 179585658320534.6],
  [1749081600000, 178948840966760.94],
  [1749168000000, 173498311645619.7],
  [1749254400000, 178027023469230.2],
  [1749340800000, 180204160164195.62],
  [1749427200000, 180205822652402.1],
  [1749513600000, 187967193249811.56],
  [1749600000000, 187524509763221.47],
  [1749686400000, 184575081521565.3],
  [1749772800000, 180624143535765.12],
  [1749859200000, 181539805900760.34],
  [1749945600000, 180636698742719.03],
  [1750032000000, 180723901772300.84],
  [1750118400000, 183221269148744.34],
  [1750204800000, 179702316313150.78],
  [1750291200000, 180302143667231.16],
  [1750377600000, 180531137316963.9],
  [1750464000000, 177890103970304.6],
  [1750550400000, 174711454616211.44],
  [1750636800000, 173609591377867.56],
  [1750723200000, 181149919791061.84],
  [1750809600000, 181156284017729.62],
  [1750896000000, 183375534968167.0],
  [1750982400000, 182252346979144.12],
  [1751068800000, 182050553824902.0],
  [1751155200000, 182496862611105.2],
  [1751241600000, 184172362843128.75],
  [1751328000000, 182589937080075.4],
  [1751414400000, 180042186852721.9],
  [1751500800000, 185433877443111.84],
  [1751587200000, 186153377423026.12],
  [1751673600000, 183964052155743.7],
  [1751760000000, 184674889643392.38],
  [1751846400000, 185655570923395.9],
  [1751932800000, 184993020620040.47],
  [1752019200000, 185732711341357.97],
  [1752105600000, 189862956245589.16],
  [1752192000000, 197472885391991.06],
  [1752278400000, 200727427668076.25],
  [1752364800000, 200459098474667.5],
  [1752451200000, 203315574509896.47],
  [1752537600000, 204934287036692.16],
  [1752624000000, 201329642820657.56],
  [1752710400000, 202964035111987.44],
  [1752796800000, 204467504015373.97],
  [1752883200000, 202194802954273.38],
  [1752969600000, 202042587795977.12],
  [1753056000000, 201050515863258.1],
  [1753142400000, 201670805141508.38],
  [1753228800000, 206145479119255.44],
  [1753315200000, 203895633737564.28],
  [1753401600000, 203523367873936.34],
  [1753488000000, 202325740297391.03],
  [1753574400000, 203017861799776.94],
  [1753660800000, 205584489488322.06],
  [1753747200000, 203882439269756.53],
  [1753833600000, 204174804126429.94],
  [1753920000000, 205475160109208.53],
  [1754006400000, 201418598950867.1],
  [1754092800000, 196440187132600.3],
  [1754179200000, 195292182084368.75],
  [1754265600000, 198291846642595.6],
  [1754352000000, 201486748276313.56],
  [1754438400000, 199270892939290.16],
  [1754524800000, 200914827967105.34],
  [1754611200000, 204393470495470.22],
  [1754697600000, 203793891638644.78],
  [1754784000000, 203416381978669.38],
  [1754870400000, 207706349052045.0],
  [1754956800000, 207244778123923.12],
  [1755043200000, 209609141993351.22],
  [1755129600000, 215031000029612.2],
  [1755216000000, 206957101711685.75],

In [8]:
df_top3_crypto_bitcoin = pd.DataFrame({
    'price': [x[1] for x in top3_crypto_bitcoin['prices']],
    'date': pd.to_datetime([x[0] for x in top3_crypto_bitcoin['prices']], unit='ms')
})
df_top3_crypto_bitcoin['date'] = df_top3_crypto_bitcoin['date'].dt.date

In [9]:
df_top3_crypto_bitcoin.head()

          price        date
0  7.311397e+06  2025-03-13
1  7.049332e+06  2025-03-14
2  7.301206e+06  2025-03-15
3  7.337203e+06  2025-03-16
4  7.182715e+06  2025-03-17

### 2.2.2 Ethereum

In [10]:
coin_id = "ethereum"
url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"
response = rq.get(url)

if response.status_code == 200:
    top3_crypto_ethereum = response.json()

In [11]:
top3_crypto_ethereum

{'prices': [[1741824000000, 166533.75651871518],
  [1741910400000, 161919.08161409126],
  [1741996800000, 166129.37514050907],
  [1742083200000, 168649.33224748378],
  [1742169600000, 164134.74219204995],
  [1742256000000, 167679.9006033522],
  [1742342400000, 167319.001543521],
  [1742428800000, 177917.82793888426],
  [1742515200000, 171006.12473780697],
  [1742601600000, 168930.37673281875],
  [1742688000000, 170229.9761188356],
  [1742774400000, 172085.9718554942],
  [1742860800000, 177753.92370784696],
  [1742947200000, 177052.68464483944],
  [1743033600000, 172151.5682806194],
  [1743120000000, 171697.82772804037],
  [1743206400000, 162266.37796915465],
  [1743292800000, 156474.22180351955],
  [1743379200000, 154426.70647452315],
  [1743465600000, 155840.4924805317],
  [1743552000000, 163227.64895741257],
  [1743638400000, 153890.04212059852],
  [1743724800000, 155066.27550185894],
  [1743811200000, 155313.1292931023],
  [1743897600000, 154802.90633012433],
  [1743984000000, 134677.50142669896],
  [1744070400000, 133837.57278106204],
  [1744156800000, 127176.85742857557],
  [1744243200000, 143324.73934384843],
  [1744329600000, 131454.92128790365],
  [1744416000000, 134990.81789744264],
  [1744502400000, 141499.98989505236],
  [1744588800000, 137163.51905527923],
  [1744675200000, 139502.26918137303],
  [1744761600000, 136118.34029958773],
  [1744848000000, 135084.25007491114],
  [1744934400000, 135202.85645156694],
  [1745020800000, 135687.4227659859],
  [1745107200000, 137898.7403436233],
  [1745193600000, 135372.22120159038],
  [1745280000000, 134334.00818529903],
  [1745366400000, 149984.44480204728],
  [1745452800000, 153384.6912264906],
  [1745539200000, 150793.82263866183],
  [1745625600000, 152736.0854367373],
  [1745712000000, 155508.64352977095],
  [1745798400000, 153154.64715995087],
  [1745884800000, 153246.47199208362],
  [1745971200000, 153045.86830616],
  [1746057600000, 151706.98921091956],
  [1746144000000, 155745.16924065605],
  [1746230400000, 155840.93772632716],
  [1746316800000, 155254.81405305702],
  [1746403200000, 152837.10606631296],
  [1746489600000, 153282.69389658255],
  [1746576000000, 153903.86052217713],
  [1746662400000, 153546.46543390723],
  [1746748800000, 189067.0538600533],
  [1746835200000, 199979.47617304884],
  [1746921600000, 220672.16056835878],
  [1747008000000, 214170.10011952536],
  [1747094400000, 211740.19586880849],
  [1747180800000, 227649.06017478785],
  [1747267200000, 222550.86125964453],
  [1747353600000, 217226.91460543944],
  [1747440000000, 217756.90685748137],
  [1747526400000, 211823.19396124792],
  [1747612800000, 210787.9756927576],
  [1747699200000, 215738.55684027018],
  [1747785600000, 215915.19935485243],
  [1747872000000, 219047.5756337483],
  [1747958400000, 228450.3696380665],
  [1748044800000, 214375.8056090152],
  [1748131200000, 215195.01779836757],
  [1748217600000, 216970.8522801864],
  [1748304000000, 218190.67523487698],
  [1748390400000, 227238.5848495167],
  [1748476800000, 228525.93909568293],
  [1748563200000, 224768.84403505738],
  [1748649600000, 216016.02336935312],
  [1748736000000, 216690.8648491384],
  [1748822400000, 217089.5740742275],
  [1748908800000, 222777.49872829148],
  [1748995200000, 222455.17860950096],
  [1749081600000, 224236.44416331983],
  [1749168000000, 207961.65418872624],
  [1749254400000, 212876.9182145838],
  [1749340800000, 216727.81140618862],
  [1749427200000, 215217.42336418747],
  [1749513600000, 230255.54711844953],
  [1749600000000, 240556.86572695823],
  [1749686400000, 237276.58179525606],
  [1749772800000, 227345.61024210224],
  [1749859200000, 221936.8494721614],
  [1749945600000, 218235.52611319744],
  [1750032000000, 219421.86983518038],
  [1750118400000, 220541.89744913176],
  [1750204800000, 217182.0562912451],
  [1750291200000, 218382.42014738446],
  [1750377600000, 218767.0130883784],
  [1750464000000, 208337.07852694736],
  [1750550400000, 196636.0383307714],
  [1750636800000, 192852.03096719063],
  [1750723200000, 209315.24780590468],
  [1750809600000, 210338.28060317386],
  [1750896000000, 207894.42363255343],
  [1750982400000, 206903.99097231845],
  [1751068800000, 207191.0496905718],
  [1751155200000, 208396.95938860573],
  [1751241600000, 213866.80820581852],
  [1751328000000, 213247.902753943],
  [1751414400000, 206191.53795072352],
  [1751500800000, 220583.0677146267],
  [1751587200000, 221209.20718607036],
  [1751673600000, 214841.71925105614],
  [1751760000000, 215995.5389160479],
  [1751846400000, 219842.28509645213],
  [1751932800000, 218478.50703220506],
  [1752019200000, 224192.01293457407],
  [1752105600000, 237634.3285912139],
  [1752192000000, 252785.18261104374],
  [1752278400000, 253963.71411998925],
  [1752364800000, 252599.85968309751],
  [1752451200000, 255256.0749124428],
  [1752537600000, 258953.02296009834],
  [1752624000000, 269423.17285168904],
  [1752710400000, 289273.06195820443],
  [1752796800000, 299604.7001320289],
  [1752883200000, 305580.9799247014],
  [1752969600000, 309629.88231970003],
  [1753056000000, 323799.5635112756],
  [1753142400000, 324888.02667051577],
  [1753228800000, 323522.2855073287],
  [1753315200000, 313632.80993368995],
  [1753401600000, 320521.28663827025],
  [1753488000000, 322067.53188592376],
  [1753574400000, 323729.6744159729],
  [1753660800000, 334271.3356334813],
  [1753747200000, 328567.3072022601],
  [1753833600000, 329848.44489638496],
  [1753920000000, 333798.49786685634],
  [1754006400000, 323419.73918441863],
  [1754092800000, 303617.9116663577],
  [1754179200000, 296151.6805356246],
  [1754265600000, 305147.6597239278],
  [1754352000000, 326586.85608261486],
  [1754438400000, 316895.55183794844],
  [1754524800000, 323322.0010279766],
  [1754611200000, 341975.0422938313],
  [1754697600000, 352049.4403810017],
  [1754784000000, 374193.3376648639],
  [1754870400000, 372140.5970629246],
  [1754956800000, 370718.8174494866],
  [1755043200000, 403547.06190802733],
  [1755129600000, 416582.6051270567],
  [1755216000000, 399375.2127189976],
  [1755302400000, 387732.95356370165],
  [1755388800000, 387408.6664674909],
  [1755475200000, 392681.4189909559],
  [1755561600000, 376878.0982824829],
  [1755648000000, 354772.70430919825],
  [1755734400000, 376832.66666282027],
  [1755820800000, 368766.6639472321],
  [1755907200000, 421737.4738716338],
  [1755993600000, 416904.49092835333],
  [1756080000000, 417273.9071184703],
  [1756166400000, 383869.2304155191],
  [1756252800000, 403346.84673449927],
  [1756339200000, 394479.82107990474],
  [1756425600000, 394824.62858350464],
  [1756512000000, 384794.36172029114],
  [1756598400000, 385618.86285304534],
  [1756684800000, 386992.0744205619],
  [1756771200000, 378688.487081064],
  [1756857600000, 380669.0608269572],
  [1756944000000, 391914.25736500154],
  [1757030400000, 379062.50711160863],
  [1757116800000, 379789.69451721257],
  [1757203200000, 376830.61714539555],
  [1757289600000, 379557.7315665512],
  [1757376000000, 379169.3803941581],
  [1757462400000, 380163.9598970403],
  [1757548800000, 382811.6356012148],
  [1757635200000, 393614.0739117057],
  [1757721600000, 415686.0060768963],
  [1757808000000, 412052.856085073],
  [1757894400000, 406940.596240047],
  [1757980800000, 398693.42995223537],
  [1758067200000, 395856.797622927],
  [1758153600000, 403666.7568900215],
  [1758240000000, 404926.98327490315],
  [1758326400000, 393846.3358485685],
  [1758412800000, 394843.6203459821],
  [1758499200000, 392295.47524281475],
  [1758585600000, 370875.27142150694],
  [1758672000000, 369992.0919011612],
  [1758758400000, 368312.96560615575],
  [1758844800000, 342937.4440185811],
  [1758931200000, 357978.55612770614],
  [1759017600000, 356321.1005771281],
  [1759104000000, 367286.12298418215],
  [1759190400000, 373944.85329388455],
  [1759276800000, 368177.3713848715],
  [1759363200000, 385235.77973544877],
  [1759449600000, 397823.05193989933],
  [1759536000000, 400707.46142882656],
  [1759622400000, 398218.8935895547],
  [1759708800000, 400668.6421398132],
  [1759795200000, 416041.06085392536],
  [1759881600000, 395289.8026309068],
  [1759968000000, 401911.0484708849],
  [1760054400000, 388222.87205311254],
  [1760140800000, 340432.9353676543],
  [1760227200000, 332747.98798714374],
  [1760313600000, 369207.3362657844],
  [1760400000000, 376492.3574048653],
  [1760486400000, 366574.05838423775],
  [1760572800000, 349761.3884710538],
  [1760659200000, 342302.33220614656],
  [1760745600000, 337247.7588866496],
  [1760832000000, 342375.6803081046],
  [1760918400000, 350696.6804336402],
  [1761004800000, 349657.073530753],
  [1761091200000, 341303.9842640361],
  [1761177600000, 333571.21535914514],
  [1761264000000, 338462.9290819708],
  [1761350400000, 345416.6546043208],
  [1761436800000, 347083.5922685809],
  [1761523200000, 365539.5621120337],
  [1761609600000, 363758.94232227415],
  [1761696000000, 351342.5325721324],
  [1761782400000, 344315.5289450759],
  [1761868800000, 337015.4990615576],
  [1761955200000, 341801.10296794504],
  [1762041600000, 343730.3913686987],
  [1762128000000, 347169.85800323385],
  [1762214400000, 319468.25832003524],
  [1762300800000, 292527.2014230804],
  [1762387200000, 303546.1807953054],
  [1762473600000, 293412.52766766545],
  [1762560000000, 304507.99491275364],
  [1762646400000, 301591.6290594234],
  [1762732800000, 317071.7291616941],
  [1762819200000, 316207.1597353334],
  [1762905600000, 302271.19106009],
  [1762992000000, 302072.2252489844],
  [1763078400000, 287385.51825001417],
  [1763164800000, 275511.26516527805],
  [1763251200000, 281155.6844835739],
  [1763337600000, 275080.20597856207],
  [1763424000000, 267796.5731112152],
  [1763510400000, 276052.04898099863],
  [1763596800000, 267032.830083096],
  [1763683200000, 251183.08126814634],
  [1763769600000, 247777.39778764817],
  [1763856000000, 248183.09115512334],
  [1763942400000, 250950.12836319354],
  [1764028800000, 263283.40358322934],
  [1764115200000, 263444.9399900479],
  [1764201600000, 269938.1970950932],
  [1764288000000, 269490.2527975858],
  [1764374400000, 271004.1486761167],
  [1764460800000, 267260.2384447111],
  [1764547200000, 267424.4592587914],
  [1764633600000, 250829.94408877468],
  [1764720000000, 269370.30418167287],
  [1764806400000, 288132.42535713845],
  [1764892800000, 281520.95159888716],
  [1764979200000, 271893.52182715805],
  [1765065600000, 273416.13820120675],
  [1765152000000, 274616.2375638853],
  [1765238400000, 281685.69218486216],
  [1765324800000, 298746.9630305986],
  [1765411200000, 298675.7147486205],
  [1765497600000, 292065.55714175856],
  [1765584000000, 279306.9974351619],
  [1765670400000, 282191.1596649078],
  [1765756800000, 277686.2575249929],
  [1765843200000, 269107.8224748998],
  [1765929600000, 269596.8374095658],
  [1766016000000, 255672.94816147196],
  [1766102400000, 255132.82641488407],
  [1766188800000, 266653.5750632806],
  [1766275200000, 266686.3060581252],
  [1766361600000, 268857.45721078233],
  [1766448000000, 269330.66898642445],
  [1766534400000, 265308.33057719615],
  [1766620800000, 264638.4624631536],
  [1766707200000, 261698.83888170918],
  [1766793600000, 262776.73658441985],
  [1766880000000, 264850.5744899021],
  [1766966400000, 264760.5504658988],
  [1767052800000, 263786.42273046816],
  [1767139200000, 266620.8671552428],
  [1767225600000, 266951.6312463789],
  [1767312000000, 269940.3569195695],
  [1767398400000, 281016.1719855551],
  [1767484800000, 281388.8695194364],
  [1767571200000, 282560.6030133936],
  [1767657600000, 291299.3568651643],
  [1767744000000, 297045.36579862604],
  [1767830400000, 284403.12191626645],
  [1767916800000, 279086.945835317],
  [1768003200000, 278309.6101406161],
  [1768089600000, 278294.1933407241],
  [1768176000000, 281519.50124331604],
  [1768262400000, 278535.9889192714],
  [1768348800000, 299728.9177688779],
  [1768435200000, 302917.5844429012],
  [1768521600000, 299838.3615803796],
  [1768608000000, 299041.3190188698],
  [1768694400000, 300496.6677650833],
  [1768780800000, 297943.7602436932],
  [1768867200000, 289592.03165583033],
  [1768953600000, 267489.81096221146],
  [1769040000000, 272419.05713641306],
  [1769126400000, 269940.0485702116],
  [1769212800000, 270322.79786255566],
  [1769299200000, 270125.836049164],
  [1769385600000, 257898.21011062048],
  [1769472000000, 268521.1124032741],
  [1769558400000, 276537.237355733],
  [1769644800000, 276752.68161058764],
  [1769731200000, 258717.1664228855],
  [1769817600000, 247763.65614624374],
  [1769904000000, 224065.64499097393],
  [1769990400000, 208098.68569226892],
  [1770076800000, 212055.7416695305],
  [1770163200000, 201371.05394647823],
  [1770249600000, 194638.91147198106],
  [1770336000000, 164424.8093049238],
  [1770422400000, 186695.3649137571],
  [1770508800000, 189440.9269478321],
  [1770595200000, 189754.81871261535],
  [1770681600000, 191035.83888725925],
  [1770768000000, 182890.5822309681],
  [1770854400000, 175976.56404532818],
  [1770940800000, 176214.23834483154],
  [1771027200000, 185411.2111430372],
  [1771113600000, 188855.60230133013],
  [1771200000000, 177856.25063894037],
  [1771286400000, 181624.1547003928],
  [1771372800000, 180528.32834312637],
  [1771459200000, 177478.4599141033],
  [1771545600000, 177249.2474816647],
  [1771632000000, 178533.39457288812],
  [1771718400000, 179064.34776215904],
  [1771804800000, 177305.13210485573],
  [1771891200000, 168724.9961412896],
  [1771977600000, 168454.26945512652],
  [1772064000000, 186740.27349943476],
  [1772150400000, 184470.53087042045],
  [1772236800000, 175906.3206947476],
  [1772323200000, 178968.6577342996],
  [1772409600000, 176523.67517814328],
  [1772496000000, 185826.30723370606],
  [1772582400000, 182403.7063918738],
  [1772668800000, 195838.5762971537],
  [1772755200000, 190414.48477250861],
  [1772841600000, 182113.64679332406],
  [1772928000000, 181094.53416839553],
  [1773014400000, 178231.25313766958],
  [1773100800000, 183916.21187136925],
  [1773187200000, 187187.4516331626],
  [1773273600000, 189229.2165179718],
  [1773296752000, 187247.35713944593]],
 'market_caps': [[1741824000000, 20085603516222.754],
  [1741910400000, 19528056390887.465],
  [1741996800000, 20039599120089.156],
  [1742083200000, 20341903585848.312],
  [1742169600000, 19796786834929.07],
  [1742256000000, 20227824871274.645],
  [1742342400000, 20183598612149.277],
  [1742428800000, 21449137942987.957],
  [1742515200000, 20631516830468.668],
  [1742601600000, 20377973662622.49],
  [1742688000000, 20531473680466.844],
  [1742774400000, 20760274608537.34],
  [1742860800000, 21443393407704.555],
  [1742947200000, 21346694911099.812],
  [1743033600000, 20757683912984.38],
  [1743120000000, 20705241587873.46],
  [1743206400000, 19570694822017.227],
  [1743292800000, 18840993550591.625],
  [1743379200000, 18629084276069.793],
  [1743465600000, 18786560281779.637],
  [1743552000000, 19687587221507.855],
  [1743638400000, 18567596273779.742],
  [1743724800000, 18741687348290.824],
  [1743811200000, 18739279793377.004],
  [1743897600000, 18641765753867.99],
  [1743984000000, 16275886364800.69],
  [1744070400000, 16220156827735.78],
  [1744156800000, 15341850606795.852],
  [1744243200000, 17295439388707.207],
  [1744329600000, 15867388978846.139],
  [1744416000000, 16285830907016.555],
  [1744502400000, 17082558690872.648],
  [1744588800000, 16539741203290.22],
  [1744675200000, 16834983359648.28],
  [1744761600000, 16445505463271.52],
  [1744848000000, 16303860358764.06],
  [1744934400000, 16319841285772.947],
  [1745020800000, 16382176256942.48],
  [1745107200000, 16645102148507.918],
  [1745193600000, 16340267652649.816],
  [1745280000000, 16212334031425.324],
  [1745366400000, 18118959580873.656],
  [1745452800000, 18516978381330.01],
  [1745539200000, 18203167257176.23],
  [1745625600000, 18439254508926.66],
  [1745712000000, 18770174800199.71],
  [1745798400000, 18488745565907.793],
  [1745884800000, 18502319366103.516],
  [1745971200000, 18447291430733.875],
  [1746057600000, 18317929977876.984],
  [1746144000000, 18800126168118.516],
  [1746230400000, 18810738491699.42],
  [1746316800000, 18745228432327.53],
  [1746403200000, 18445057430426.93],
  [1746489600000, 18509252303957.832],
  [1746576000000, 18584188256260.402],
  [1746662400000, 18538514313028.895],
  [1746748800000, 22798829831788.9],
  [1746835200000, 24139980478786.055],
  [1746921600000, 26656063329629.605],
  [1747008000000, 25856797670358.043],
  [1747094400000, 25569016632392.3],
  [1747180800000, 27469315165105.24],
  [1747267200000, 26840801328902.758],
  [1747353600000, 26225966154628.168],
  [1747440000000, 26327092615697.6],
  [1747526400000, 25571404265146.887],
  [1747612800000, 25381979032540.83],
  [1747699200000, 26045570271704.777],
  [1747785600000, 26065746402884.008],
  [1747872000000, 26444983799263.41],
  [1747958400000, 27575144381363.11],
  [1748044800000, 25866414485869.51],
  [1748131200000, 25979607695617.562],
  [1748217600000, 26192351730004.07],
  [1748304000000, 26341157306904.684],
  [1748390400000, 27431354286670.96],
  [1748476800000, 27591067621067.95],
  [1748563200000, 27135655870963.168],
  [1748649600000, 26069341890584.62],
  [1748736000000, 26159919819506.07],
  [1748822400000, 26218561663815.895],
  [1748908800000, 26890206841193.1],
  [1748995200000, 26854002340422.105],
  [1749081600000, 27073188663150.395],
  [1749168000000, 25105666011201.39],
  [1749254400000, 25698932035424.312],
  [1749340800000, 26161626042356.97],
  [1749427200000, 25981876177541.71],
  [1749513600000, 27812086680388.97],
  [1749600000000, 29037433538570.996],
  [1749686400000, 28631635860089.63],
  [1749772800000, 27471428774360.684],
  [1749859200000, 26793081377844.934],
  [1749945600000, 26357064203017.953],
  [1750032000000, 26485275895269.984],
  [1750118400000, 26690900915754.188],
  [1750204800000, 26225875723581.453],
  [1750291200000, 26355724035661.523],
  [1750377600000, 26409878632339.363],
  [1750464000000, 25149264907246.125],
  [1750550400000, 23714942731298.484],
  [1750636800000, 23270927894103.484],
  [1750723200000, 25268493846150.977],
  [1750809600000, 25396878797991.395],
  [1750896000000, 25098724913873.09],
  [1750982400000, 24977830864460.324],
  [1751068800000, 25004501053435.465],
  [1751155200000, 25157501767716.855],
  [1751241600000, 25821101946020.94],
  [1751328000000, 25744526128484.51],
  [1751414400000, 24887175924395.695],
  [1751500800000, 26645767784128.19],
  [1751587200000, 26699275505892.14],
  [1751673600000, 25928200797375.027],
  [1751760000000, 26086206245551.16],
  [1751846400000, 26533485698216.99],
  [1751932800000, 26370086338998.305],
  [1752019200000, 27061213234333.78],
  [1752105600000, 28716730871244.258],
  [1752192000000, 30465670349809.316],
  [1752278400000, 30654337408657.83],
  [1752364800000, 30488887456205.07],
  [1752451200000, 30819385404917.04],
  [1752537600000, 31258740549392.49],
  [1752624000000, 32525540543934.215],
  [1752710400000, 34921000730302.3],
  [1752796800000, 36169518489813.67],
  [1752883200000, 36856118013008.92],
  [1752969600000, 37376067302248.95],
  [1753056000000, 39096577669726.35],
  [1753142400000, 39215960978366.26],
  [1753228800000, 39057793349594.484],
  [1753315200000, 37852379251737.85],
  [1753401600000, 38688029004178.16],
  [1753488000000, 38874177075130.98],
  [1753574400000, 39077196730448.59],
  [1753660800000, 40318677556180.195],
  [1753747200000, 39716565448057.98],
  [1753833600000, 39806613299714.71],
  [1753920000000, 40280171870311.266],
  [1754006400000, 39043500652196.35],
  [1754092800000, 36638665425892.56],
  [1754179200000, 35758874484246.82],
  [1754265600000, 36837160842306.984],
  [1754352000000, 39421772450523.08],
  [1754438400000, 38280178186972.52],
  [1754524800000, 39031410608883.41],
  [1754611200000, 41253983001617.69],
  [1754697600000, 42502679661655.32],
  [1754784000000, 45126662598702.41],
  [1754870400000, 44888072846811.18],

In [12]:
df_top3_crypto_ethereum = pd.DataFrame({
    'price': [x[1] for x in top3_crypto_ethereum['prices']],
    'date': pd.to_datetime([x[0] for x in top3_crypto_ethereum['prices']], unit='ms')
})
df_top3_crypto_ethereum['date'] = df_top3_crypto_ethereum['date'].dt.date

In [13]:
df_top3_crypto_ethereum

             price        date
0    166533.756519  2025-03-13
1    161919.081614  2025-03-14
2    166129.375141  2025-03-15
3    168649.332247  2025-03-16
4    164134.742192  2025-03-17
..             ...         ...
361  178231.253138  2026-03-09
362  183916.211871  2026-03-10
363  187187.451633  2026-03-11
364  189229.216518  2026-03-12
365  187247.357139  2026-03-12

[366 rows x 2 columns]

### 2.2.3 Tether

In [23]:
coin_id = "tether"
url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"
response = rq.get(url)

if response.status_code == 200:
    top3_crypto_tether = response.json()

In [24]:
response.status_code

200

In [25]:
top3_crypto_tether

{'prices': [[1741824000000, 87.13812439531706],
  [1741910400000, 86.88227677312257],
  [1741996800000, 86.94921680100975],
  [1742083200000, 86.94389363361535],
  [1742169600000, 86.93794292174915],
  [1742256000000, 86.91162498732017],
  [1742342400000, 86.55062124305569],
  [1742428800000, 86.35903278492714],
  [1742515200000, 86.27903846450975],
  [1742601600000, 85.95866042648954],
  [1742688000000, 85.9799918495505],
  [1742774400000, 85.99487545180361],
  [1742860800000, 85.56623682089695],
  [1742947200000, 85.60505163395878],
  [1743033600000, 85.65936651729078],
  [1743120000000, 85.67335919646858],
  [1743206400000, 85.50070025979748],
  [1743292800000, 85.51084614037516],
  [1743379200000, 85.52084756288973],
  [1743465600000, 85.41206359379504],
  [1743552000000, 85.5849496864284],
  [1743638400000, 85.6761598207736],
  [1743724800000, 85.24511390484845],
  [1743811200000, 85.5661985291957],
  [1743897600000, 85.49568968485505],
  [1743984000000, 85.45426169674982],
  [1744070400000, 85.98356950367794],
  [1744156800000, 86.35241410213946],
  [1744243200000, 86.18814526365533],
  [1744329600000, 86.21000906223857],
  [1744416000000, 86.04341248201443],
  [1744502400000, 85.96411661704484],
  [1744588800000, 85.94839986278411],
  [1744675200000, 86.02483249955277],
  [1744761600000, 85.72212946217893],
  [1744848000000, 85.62082361532676],
  [1744934400000, 85.38406088965168],
  [1745020800000, 85.37037204912903],
  [1745107200000, 85.37573578611993],
  [1745193600000, 85.38151888919427],
  [1745280000000, 85.15997232308388],
  [1745366400000, 85.26928353549717],
  [1745452800000, 85.53309052358021],
  [1745539200000, 85.25665212218877],
  [1745625600000, 85.43692338751637],
  [1745712000000, 85.4124937469656],
  [1745798400000, 85.41364771445048],
  [1745884800000, 85.1792488506429],
  [1745971200000, 85.19186692504695],
  [1746057600000, 84.56842522735435],
  [1746144000000, 84.72143692477849],
  [1746230400000, 84.66198576779752],
  [1746316800000, 84.64989023486065],
  [1746403200000, 84.52978130383568],
  [1746489600000, 84.21417463632208],
  [1746576000000, 84.73599019648395],
  [1746662400000, 84.83282740724479],
  [1746748800000, 86.02914921640757],
  [1746835200000, 85.41568222748235],
  [1746921600000, 85.41712733923939],
  [1747008000000, 85.42898961498291],
  [1747094400000, 84.95652139253393],
  [1747180800000, 85.06156417476146],
  [1747267200000, 85.48823723690717],
  [1747353600000, 85.45656192963469],
  [1747440000000, 85.60168980329202],
  [1747526400000, 85.6092168588343],
  [1747612800000, 85.5270435261299],
  [1747699200000, 85.39817385178996],
  [1747785600000, 85.5574306577747],
  [1747872000000, 85.63163566501078],
  [1747958400000, 85.99115187130867],
  [1748044800000, 85.08388346482636],
  [1748131200000, 85.09325889425735],
  [1748217600000, 85.22865612080716],
  [1748304000000, 85.18093962269563],
  [1748390400000, 85.39669345824056],
  [1748476800000, 85.4052947205679],
  [1748563200000, 85.35724386429538],
  [1748649600000, 85.58984664926011],
  [1748736000000, 85.59658469286101],
  [1748822400000, 85.5563529489217],
  [1748908800000, 85.39681423567808],
  [1748995200000, 85.7564471650407],
  [1749081600000, 85.93913530548173],
  [1749168000000, 85.90869091197705],
  [1749254400000, 85.84476147301244],
  [1749340800000, 85.82584934522494],
  [1749427200000, 85.81535004059877],
  [1749513600000, 85.78084450272435],
  [1749600000000, 85.65857775303438],
  [1749686400000, 85.4820574765995],
  [1749772800000, 85.71186331793116],
  [1749859200000, 86.14792041627604],
  [1749945600000, 86.14647537272096],
  [1750032000000, 86.12327231151762],
  [1750118400000, 86.13602992064845],
  [1750204800000, 86.35699142609901],
  [1750291200000, 86.62723601577105],
  [1750377600000, 86.74229506504231],
  [1750464000000, 86.60305512132527],
  [1750550400000, 86.6169466622025],
  [1750636800000, 86.59580048336504],
  [1750723200000, 86.40380690891152],
  [1750809600000, 86.00974451148616],
  [1750896000000, 86.04675823077042],
  [1750982400000, 85.70312960692094],
  [1751068800000, 85.53787082600891],
  [1751155200000, 85.5325791073527],
  [1751241600000, 85.46600406267324],
  [1751328000000, 85.72185130518295],
  [1751414400000, 85.73789654348656],
  [1751500800000, 85.72260504432407],
  [1751587200000, 85.42620080018943],
  [1751673600000, 85.63834651243872],
  [1751760000000, 85.81550473224671],
  [1751846400000, 85.50080347794888],
  [1751932800000, 85.8931511462235],
  [1752019200000, 85.71745265403365],
  [1752105600000, 85.72963895170048],
  [1752192000000, 85.7367951539024],
  [1752278400000, 85.85227877587944],
  [1752364800000, 85.85061649402768],
  [1752451200000, 85.84713404704165],
  [1752537600000, 85.9788836587437],
  [1752624000000, 85.99614027111835],
  [1752710400000, 85.92092361254213],
  [1752796800000, 86.09793480404404],
  [1752883200000, 86.18837553232646],
  [1752969600000, 86.18240819304249],
  [1753056000000, 86.18316667030595],
  [1753142400000, 86.30931582921966],
  [1753228800000, 86.374857116835],
  [1753315200000, 86.43062185519801],
  [1753401600000, 86.46549430247569],
  [1753488000000, 86.5079067153148],
  [1753574400000, 86.52243726818574],
  [1753660800000, 86.52789458004021],
  [1753747200000, 86.77257651023056],
  [1753833600000, 87.0447381138731],
  [1753920000000, 87.66199308684169],
  [1754006400000, 87.47687374098898],
  [1754092800000, 87.12827066746021],
  [1754179200000, 87.14631032765092],
  [1754265600000, 87.24786620155615],
  [1754352000000, 87.88635216255223],
  [1754438400000, 87.71607532269402],
  [1754524800000, 87.77852723054042],
  [1754611200000, 87.4444950197738],
  [1754697600000, 87.7304688799895],
  [1754784000000, 87.73905734147515],
  [1754870400000, 87.49382998052141],
  [1754956800000, 87.66325855501688],
  [1755043200000, 87.57426395817158],
  [1755129600000, 87.47159503365995],
  [1755216000000, 87.7507816372641],
  [1755302400000, 87.57103102116423],
  [1755388800000, 87.56566303963238],
  [1755475200000, 87.56915502746656],
  [1755561600000, 87.3340088432775],
  [1755648000000, 87.06237707950677],
  [1755734400000, 87.02531092350665],
  [1755820800000, 87.27411100595894],
  [1755907200000, 87.30311165905988],
  [1755993600000, 87.29882406170462],
  [1756080000000, 87.3250208029963],
  [1756166400000, 87.62524577288721],
  [1756252800000, 87.6555295525574],
  [1756339200000, 87.668600994889],
  [1756425600000, 87.60195342039783],
  [1756512000000, 88.18667861075136],
  [1756598400000, 88.19307898655691],
  [1756684800000, 88.18864003171554],
  [1756771200000, 88.00873910734951],
  [1756857600000, 88.00002982554487],
  [1756944000000, 88.10692319228819],
  [1757030400000, 88.20504329957987],
  [1757116800000, 88.20372141914076],
  [1757203200000, 88.21983030547217],
  [1757289600000, 88.18847972275259],
  [1757376000000, 87.98584666444708],
  [1757462400000, 88.22328147418891],
  [1757548800000, 88.0799119922726],
  [1757635200000, 88.30068969250112],
  [1757721600000, 88.33560397637382],
  [1757808000000, 88.32785330203377],
  [1757894400000, 88.3351205913677],
  [1757980800000, 88.15077362664188],
  [1758067200000, 87.91150541711174],
  [1758153600000, 87.93977895055079],
  [1758240000000, 88.23765391962607],
  [1758326400000, 88.13802082148666],
  [1758412800000, 88.139164151048],
  [1758499200000, 88.1346583356557],
  [1758585600000, 88.37661271837068],
  [1758672000000, 88.82656484403672],
  [1758758400000, 88.80868751998199],
  [1758844800000, 88.81435164667624],
  [1758931200000, 88.72140292397307],
  [1759017600000, 88.71734688895152],
  [1759104000000, 88.70541085832512],
  [1759190400000, 88.7491896902959],
  [1759276800000, 88.8426089698473],
  [1759363200000, 88.72426143807172],
  [1759449600000, 88.76512104961576],
  [1759536000000, 88.78362210279245],
  [1759622400000, 88.76623479806274],
  [1759708800000, 88.75366387498042],
  [1759795200000, 88.75288542329216],
  [1759881600000, 88.77735469974357],
  [1759968000000, 88.78940863615091],
  [1760054400000, 88.91298299022279],
  [1760140800000, 88.90605760034835],
  [1760227200000, 88.89251175516847],
  [1760313600000, 88.86461911659299],
  [1760400000000, 88.75798894617424],
  [1760486400000, 88.84161342512054],
  [1760572800000, 87.87595476797446],
  [1760659200000, 88.03026630514042],
  [1760745600000, 88.09120710681987],
  [1760832000000, 88.07983302001],
  [1760918400000, 88.05341963633443],
  [1761004800000, 87.9260315917352],
  [1761091200000, 88.06928167631557],
  [1761177600000, 87.77158858695039],
  [1761264000000, 87.81763959771669],
  [1761350400000, 87.8550746128549],
  [1761436800000, 87.85314930031927],
  [1761523200000, 87.85195702568677],
  [1761609600000, 88.23580845345],
  [1761696000000, 88.25448192741274],
  [1761782400000, 88.37203661224855],
  [1761868800000, 88.64761241704615],
  [1761955200000, 88.82065097034915],
  [1762041600000, 88.75800024218165],
  [1762128000000, 88.79262580633974],
  [1762214400000, 88.71741213008899],
  [1762300800000, 88.73379965537089],
  [1762387200000, 88.5625678020861],
  [1762473600000, 88.63797690855044],
  [1762560000000, 88.6391072849014],
  [1762646400000, 88.64810924782387],
  [1762732800000, 88.63797258022694],
  [1762819200000, 88.6721395259377],
  [1762905600000, 88.40908429110375],
  [1762992000000, 88.57768259711408],
  [1763078400000, 88.75966779895626],
  [1763164800000, 88.65745562119984],
  [1763251200000, 88.65619087029994],
  [1763337600000, 88.62689987537672],
  [1763424000000, 88.54166896625892],
  [1763510400000, 88.51590926900492],
  [1763596800000, 88.4108653142146],
  [1763683200000, 88.59563784626259],
  [1763769600000, 89.58183385437731],
  [1763856000000, 89.60575823562925],
  [1763942400000, 89.61286862659206],
  [1764028800000, 89.13868923900014],
  [1764115200000, 89.1257096830021],
  [1764201600000, 89.15845599673318],
  [1764288000000, 89.36495482281371],
  [1764374400000, 89.36856427843449],
  [1764460800000, 89.37830938750452],
  [1764547200000, 89.37112064045994],
  [1764633600000, 89.61795485812628],
  [1764720000000, 89.94838626297397],
  [1764806400000, 90.19657892405961],
  [1764892800000, 89.85301183611787],
  [1764979200000, 89.97342634793257],
  [1765065600000, 89.98474906827668],
  [1765152000000, 89.97259854785385],
  [1765238400000, 90.14013168471735],
  [1765324800000, 89.92478216651145],
  [1765411200000, 89.81184332576044],
  [1765497600000, 90.2697965268675],
  [1765584000000, 90.54461267113906],
  [1765670400000, 90.59905295741481],
  [1765756800000, 90.60135439015166],
  [1765843200000, 90.78498450129678],
  [1765929600000, 90.93947274605033],
  [1766016000000, 90.39586093549374],
  [1766102400000, 90.22639439481647],
  [1766188800000, 89.53005618629385],
  [1766275200000, 89.55329537913303],
  [1766361600000, 89.55235938559296],
  [1766448000000, 89.56321616946981],
  [1766534400000, 89.42824078050577],
  [1766620800000, 89.78689321529701],
  [1766707200000, 90.06553404658248],
  [1766793600000, 89.72933722342869],
  [1766880000000, 89.76687299943417],
  [1766966400000, 89.75957578168293],
  [1767052800000, 89.80272658845097],
  [1767139200000, 89.68155241771825],
  [1767225600000, 89.86010638630553],
  [1767312000000, 89.86570510038233],
  [1767398400000, 89.97829419376352],
  [1767484800000, 89.98313618928253],
  [1767571200000, 89.9794305246393],
  [1767657600000, 90.22984949955419],
  [1767744000000, 90.11703926114808],
  [1767830400000, 89.7856606556656],
  [1767916800000, 89.82985588533627],
  [1768003200000, 90.15349935308005],
  [1768089600000, 90.15550929326064],
  [1768176000000, 90.12924081121562],
  [1768262400000, 90.03425860537745],
  [1768348800000, 90.24459865393862],
  [1768435200000, 90.24498201655751],
  [1768521600000, 90.33675913039339],
  [1768608000000, 90.69074291688807],
  [1768694400000, 90.83776783825128],
  [1768780800000, 90.68339984388055],
  [1768867200000, 90.84651949988248],
  [1768953600000, 91.01366646915989],
  [1769040000000, 91.45755919235742],
  [1769126400000, 91.47153938859708],
  [1769212800000, 91.49463866061221],
  [1769299200000, 91.46082307004623],
  [1769385600000, 91.5501111949003],
  [1769472000000, 91.61728715188963],
  [1769558400000, 91.4157096633518],
  [1769644800000, 91.90782656395334],
  [1769731200000, 91.643309265233],
  [1769817600000, 91.54713924898934],
  [1769904000000, 91.58626145922887],
  [1769990400000, 91.60327421251533],
  [1770076800000, 90.37535097601004],
  [1770163200000, 90.30711451597838],
  [1770249600000, 90.25754714478542],
  [1770336000000, 90.15474465431593],
  [1770422400000, 90.54112624507336],
  [1770508800000, 90.54490136224952],
  [1770595200000, 90.5241178608326],
  [1770681600000, 90.73829171749978],
  [1770768000000, 90.54271672929444],
  [1770854400000, 90.68273769379299],
  [1770940800000, 90.50516146580522],
  [1771027200000, 90.51813798097378],
  [1771113600000, 90.52534256474571],
  [1771200000000, 90.5230794828881],
  [1771286400000, 90.74965034353232],
  [1771372800000, 90.59527820056785],
  [1771459200000, 90.76251613145746],
  [1771545600000, 91.01080876764598],
  [1771632000000, 90.69153509343441],
  [1771718400000, 90.70613610314805],
  [1771804800000, 90.69542998936724],
  [1771891200000, 90.9952842406707],
  [1771977600000, 90.92355865051395],
  [1772064000000, 90.96825217790293],
  [1772150400000, 90.99723052968035],
  [1772236800000, 91.0843108367302],
  [1772323200000, 91.10881263967744],
  [1772409600000, 91.07060745984339],
  [1772496000000, 91.56692866442098],
  [1772582400000, 92.01194290116615],
  [1772668800000, 92.1350403232686],
  [1772755200000, 91.79147793686462],
  [1772841600000, 91.93674106068768],
  [1772928000000, 91.93855555140772],
  [1773014400000, 91.93866647186371],
  [1773100800000, 92.31427010585811],
  [1773187200000, 91.97611168078465],
  [1773273600000, 92.23382365807878],
  [1773296853000, 92.34083870309135]],
 'market_caps': [[1741824000000, 12476597517682.73],
  [1741910400000, 12454248371283.05],
  [1741996800000, 12463812032720.96],
  [1742083200000, 12473408051092.777],
  [1742169600000, 12472554177437.998],
  [1742256000000, 12468715331610.92],
  [1742342400000, 12413647231953.41],
  [1742428800000, 12386765166559.049],
  [1742515200000, 12394218834383.592],
  [1742601600000, 12337403424426.193],
  [1742688000000, 12337057670425.777],
  [1742774400000, 12339199362743.203],
  [1742860800000, 12277667025174.988],
  [1742947200000, 12308132914228.082],
  [1743033600000, 12336378395525.508],
  [1743120000000, 12353332904271.01],
  [1743206400000, 12327670514274.004],
  [1743292800000, 12329154671825.465],
  [1743379200000, 12330596709871.676],
  [1743465600000, 12294002855270.88],
  [1743552000000, 12323611454454.879],
  [1743638400000, 12339235156658.586],
  [1743724800000, 12296157210668.727],
  [1743811200000, 12328950203663.486],
  [1743897600000, 12318770335940.883],
  [1743984000000, 12312735001640.045],
  [1744070400000, 12404397094497.172],
  [1744156800000, 12451335132235.812],
  [1744243200000, 12412266751895.342],
  [1744329600000, 12446223814280.07],
  [1744416000000, 12419751302896.309],
  [1744502400000, 12412298980710.686],
  [1744588800000, 12410047009211.73],
  [1744675200000, 12417144136673.635],
  [1744761600000, 12393342766685.375],
  [1744848000000, 12383539969306.045],
  [1744934400000, 12364056765086.95],
  [1745020800000, 12361276240001.209],
  [1745107200000, 12348728444252.127],
  [1745193600000, 12349592526841.162],
  [1745280000000, 12316437324043.828],
  [1745366400000, 12340584672214.844],
  [1745452800000, 12426149291611.086],
  [1745539200000, 12417480919799.287],
  [1745625600000, 12474953149345.248],
  [1745712000000, 12566605429401.598],
  [1745798400000, 12566774818687.871],
  [1745884800000, 12542099579102.258],
  [1745971200000, 12605487511006.277],
  [1746057600000, 12551289194290.67],
  [1746144000000, 12596920364880.072],
  [1746230400000, 12606566868763.262],
  [1746316800000, 12628302445828.398],
  [1746403200000, 12624870358795.912],
  [1746489600000, 12578128987400.701],
  [1746576000000, 12661988629328.246],
  [1746662400000, 12676566205239.41],
  [1746748800000, 12861696960472.012],
  [1746835200000, 12789545468582.207],
  [1746921600000, 12802071807597.44],
  [1747008000000, 12803821979742.844],
  [1747094400000, 12748352772856.207],
  [1747180800000, 12764015135729.36],
  [1747267200000, 12852236413399.893],
  [1747353600000, 12875412641850.977],
  [1747440000000, 12930469197851.7],
  [1747526400000, 12945062569935.502],
  [1747612800000, 12939301726284.39],
  [1747699200000, 12925712718271.92],
  [1747785600000, 12969154515631.678],
  [1747872000000, 13008301740626.014],
  [1747958400000, 13105136924293.992],
  [1748044800000, 12974478317014.043],
  [1748131200000, 12993816658218.215],
  [1748217600000, 13017265179662.084],
  [1748304000000, 13009939957333.832],
  [1748390400000, 13044989781112.96],
  [1748476800000, 13059483158162.445],
  [1748563200000, 13061416804536.004],
  [1748649600000, 13102205042723.682],
  [1748736000000, 13099030376027.584],
  [1748822400000, 13098346645805.053],
  [1748908800000, 13078599504113.686],
  [1748995200000, 13147579219807.73],
  [1749081600000, 13210647248106.762],
  [1749168000000, 13215623829341.72],
  [1749254400000, 13230704278479.918],
  [1749340800000, 13257425043600.174],
  [1749427200000, 13280794882755.195],
  [1749513600000, 13276362441435.422],
  [1749600000000, 13292614783593.84],
  [1749686400000, 13252988756617.586],
  [1749772800000, 13301388458286.803],
  [1749859200000, 13369484171496.172],
  [1749945600000, 13393173150379.025],
  [1750032000000, 13387624258733.459],
  [1750118400000, 13393108750539.033],
  [1750204800000, 13426459107251.783],
  [1750291200000, 13476103401419.121],
  [1750377600000, 13507489081972.123],
  [1750464000000, 13504970735792.94],
  [1750550400000, 13502465870172.021],
  [1750636800000, 13491289311230.104],
  [1750723200000, 13476920194818.953],
  [1750809600000, 13446941499273.01],
  [1750896000000, 13482799859276.826],
  [1750982400000, 13474003370436.613],
  [1751068800000, 13470541029084.818],
  [1751155200000, 13470605292684.795],
  [1751241600000, 13467469897055.574],
  [1751328000000, 13517702204242.193],
  [1751414400000, 13522171748792.648],
  [1751500800000, 13529780228604.957],
  [1751587200000, 13520624122432.98],
  [1751673600000, 13567106471085.46],
  [1751760000000, 13609969728043.406],
  [1751846400000, 13562696484370.59],
  [1751932800000, 13621067459348.219],
  [1752019200000, 13599847763176.477],
  [1752105600000, 13602526059698.355],
  [1752192000000, 13613841514901.293],
  [1752278400000, 13657947073480.865],
  [1752364800000, 13684357811465.473],
  [1752451200000, 13691363831663.012],
  [1752537600000, 13716282329900.88],
  [1752624000000, 13749377444704.836],
  [1752710400000, 13745663547888.08],
  [1752796800000, 13798048930554.51],
  [1752883200000, 13860755623350.973],
  [1752969600000, 13922937090184.957],
  [1753056000000, 13926644906051.828],
  [1753142400000, 13952912338264.85],
  [1753228800000, 13987475645306.613],
  [1753315200000, 13996721682463.514],
  [1753401600000, 14051953741069.055],
  [1753488000000, 14104929240143.604],
  [1753574400000, 14128967945922.734],
  [1753660800000, 14153438240168.877],
  [1753747200000, 14196069479466.066],
  [1753833600000, 14245567575009.355],
  [1753920000000, 14355469476206.814],
  [1754006400000, 14324411257874.506],
  [1754092800000, 14280395127661.297],
  [1754179200000, 14283328985379.736],
  [1754265600000, 14299399006239.135],
  [1754352000000, 14405135289893.635],
  [1754438400000, 14376230477600.873],
  [1754524800000, 14379904757274.477],
  [1754611200000, 14344402879650.912],
  [1754697600000, 14417883465849.7],
  [1754784000000, 14431600662646.559],
  [1754870400000, 14393143321240.834],
  [1754956800000, 14423606522130.787],
  [1755043200000, 14417077953627.607],
  [1755129600000, 14435172306396.404],
  [1755216000000, 14481165031013.682],
  [1755302400000, 14524250808263.994],

In [26]:
df_top3_crypto_tether = pd.DataFrame({
    'price': [x[1] for x in top3_crypto_tether['prices']],
    'date': pd.to_datetime([x[0] for x in top3_crypto_tether['prices']], unit='ms')
})
df_top3_crypto_tether['date'] = df_top3_crypto_tether['date'].dt.date

In [27]:
df_top3_crypto_tether

         price        date
0    87.138124  2025-03-13
1    86.882277  2025-03-14
2    86.949217  2025-03-15
3    86.943894  2025-03-16
4    86.937943  2025-03-17
..         ...         ...
361  91.938666  2026-03-09
362  92.314270  2026-03-10
363  91.976112  2026-03-11
364  92.233824  2026-03-12
365  92.340839  2026-03-12

[366 rows x 2 columns]

## 2.3 Oil Prices

In [28]:
df_oil = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")

In [29]:
df_oil

             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10109  2026-03-03  74.48
10110  2026-03-04  74.58
10111  2026-03-05  80.88
10112  2026-03-06  90.77
10113  2026-03-09  94.65

[10114 rows x 2 columns]

## 2.4 yfinance stocks

In [30]:
stocks = yf.download(['^GSPC', '^IXIC', '^NSEI'], start='2020-01-01', end= '2025-09-30')

[*********************100%***********************]  3 of 3 completed

In [31]:
df_stocks = pd.DataFrame(stocks)

In [32]:
df_stocks

Price             Close                                     High  \
Ticker            ^GSPC         ^IXIC         ^NSEI        ^GSPC
Date
2020-01-01          NaN           NaN  12182.500000          NaN
2020-01-02  3257.850098   9092.190430  12282.200195  3258.139893
2020-01-03  3234.850098   9020.769531  12226.650391  3246.149902
2020-01-06  3246.280029   9071.469727  11993.049805  3246.840088
2020-01-07  3237.179932   9068.580078  12052.950195  3244.909912
...                 ...           ...           ...          ...
2025-09-23  6656.919922  22573.470703  25169.500000  6699.520020
2025-09-24  6637.970215  22497.859375  25056.900391  6672.660156
2025-09-25  6604.720215  22384.699219  24890.849609  6619.000000
2025-09-26  6643.700195  22484.070312  24654.699219  6648.970215
2025-09-29  6661.209961  22591.150391  24634.900391  6677.310059

Price                                           Low                \
Ticker             ^IXIC         ^NSEI        ^GSPC         ^IXIC
Date
2020-01-01           NaN  12222.200195          NaN           NaN
2020-01-02   9093.429688  12289.900391  3235.530029   9010.889648
2020-01-03   9065.759766  12265.599609  3222.340088   8976.429688
2020-01-06   9072.410156  12179.099609  3214.639893   8943.500000
2020-01-07   9091.929688  12152.150391  3232.429932   9042.549805
...                  ...           ...          ...           ...
2025-09-23  22785.130859  25261.900391  6645.580078  22539.039062
2025-09-24  22657.449219  25149.849609  6621.759766  22397.000000
2025-09-25  22456.779297  25092.699219  6569.220215  22185.869141
2025-09-26  22488.179688  24868.599609  6604.430176  22285.439453
2025-09-29  22704.900391  24791.300781  6644.490234  22536.050781

Price                            Open                              \
Ticker             ^NSEI        ^GSPC         ^IXIC         ^NSEI
Date
2020-01-01  12165.299805          NaN           NaN  12202.150391
2020-01-02  12195.250000  3244.669922   9039.459961  12198.549805
2020-01-03  12191.349609  3226.360107   8976.429688  12261.099609
2020-01-06  11974.200195  3217.550049   8943.500000  12170.599609
2020-01-07  12005.349609  3241.860107   9076.639648  12079.099609
...                  ...          ...           ...           ...
2025-09-23  25084.650391  6692.439941  22782.720703  25209.000000
2025-09-24  25027.449219  6669.790039  22656.019531  25108.750000
2025-09-25  24878.300781  6608.189941  22318.769531  25034.500000
2025-09-26  24629.449219  6615.379883  22403.269531  24818.550781
2025-09-29  24606.199219  6661.580078  22605.300781  24728.550781

Price             Volume
Ticker             ^GSPC         ^IXIC     ^NSEI
Date
2020-01-01           NaN           NaN  304100.0
2020-01-02  3.459930e+09  2.862700e+09  407700.0
2020-01-03  3.484700e+09  2.586520e+09  428800.0
2020-01-06  3.702460e+09  2.810450e+09  396500.0
2020-01-07  3.435910e+09  2.381740e+09  447800.0
...                  ...           ...       ...
2025-09-23  5.633620e+09  9.822620e+09  299200.0
2025-09-24  5.459180e+09  9.184030e+09  244400.0
2025-09-25  5.874670e+09  9.960330e+09  342500.0
2025-09-26  5.103110e+09  8.488400e+09  291500.0
2025-09-29  5.358760e+09  9.046720e+09  394400.0

[1490 rows x 15 columns]

# 3 Data Cleaning

## 3.1 Cryptocurrencies

In [33]:
df_crypto.columns = df_crypto.columns.str.upper()

In [34]:
df_crypto['LAST_UPDATED'] = pd.to_datetime(df_crypto['LAST_UPDATED']).dt.date

In [35]:
mean_value = df_crypto['TOTAL_VOLUME'].mean()

In [36]:
df_crypto['LAST_UPDATED'] = pd.to_datetime(df_crypto['LAST_UPDATED'], errors='coerce').dt.date

In [37]:
mean_value_1 = df_crypto['TOTAL_SUPPLY'].mean()

In [38]:
df_crypto.fillna({'TOTAL_VOLUME': mean_value}, inplace=True)

In [39]:
df_crypto.fillna({'TOTAL_SUPPLY': mean_value_1}, inplace=True)

In [40]:
float_cols = df_crypto.select_dtypes(include=['float64', 'float32']).columns

In [41]:
df_crypto[float_cols] = df_crypto[float_cols].round(6)

## 3.2 Crypto_prices

### 3.2.1 Bitcoin

In [42]:
df_top3_crypto_bitcoin['coin_id'] = "bitcoin"

In [43]:
column_to_move = df_top3_crypto_bitcoin.pop('coin_id')
df_top3_crypto_bitcoin.insert(0, 'coin_id', column_to_move)

In [44]:
column_to_move = df_top3_crypto_bitcoin.pop('date')
df_top3_crypto_bitcoin.insert(1, 'date', column_to_move)

In [45]:
df_top3_crypto_bitcoin

     coin_id        date         price
0    bitcoin  2025-03-13  7.311397e+06
1    bitcoin  2025-03-14  7.049332e+06
2    bitcoin  2025-03-15  7.301206e+06
3    bitcoin  2025-03-16  7.337203e+06
4    bitcoin  2025-03-17  7.182715e+06
..       ...         ...           ...
361  bitcoin  2026-03-09  6.071163e+06
362  bitcoin  2026-03-10  6.319545e+06
363  bitcoin  2026-03-11  6.427459e+06
364  bitcoin  2026-03-12  6.476953e+06
365  bitcoin  2026-03-12  6.414985e+06

[366 rows x 3 columns]

### 3.2.2 Ethereum

In [46]:
df_top3_crypto_ethereum['coin_id'] = "ethereum"

In [47]:
column_to_move = df_top3_crypto_ethereum.pop('coin_id')
df_top3_crypto_ethereum.insert(0, 'coin_id', column_to_move)

In [48]:
column_to_move = df_top3_crypto_ethereum.pop('date')
df_top3_crypto_ethereum.insert(1, 'date', column_to_move)

In [49]:
df_top3_crypto_ethereum

      coin_id        date          price
0    ethereum  2025-03-13  166533.756519
1    ethereum  2025-03-14  161919.081614
2    ethereum  2025-03-15  166129.375141
3    ethereum  2025-03-16  168649.332247
4    ethereum  2025-03-17  164134.742192
..        ...         ...            ...
361  ethereum  2026-03-09  178231.253138
362  ethereum  2026-03-10  183916.211871
363  ethereum  2026-03-11  187187.451633
364  ethereum  2026-03-12  189229.216518
365  ethereum  2026-03-12  187247.357139

[366 rows x 3 columns]

### 3.2.3 Tether

In [50]:
df_top3_crypto_tether['coin_id'] = "tether"

In [51]:
column_to_move = df_top3_crypto_tether.pop('coin_id')
df_top3_crypto_tether.insert(0, 'coin_id', column_to_move)

In [52]:
column_to_move = df_top3_crypto_tether.pop('date')
df_top3_crypto_tether.insert(1, 'date', column_to_move)

In [53]:
df_top3_crypto_tether

    coin_id        date      price
0    tether  2025-03-13  87.138124
1    tether  2025-03-14  86.882277
2    tether  2025-03-15  86.949217
3    tether  2025-03-16  86.943894
4    tether  2025-03-17  86.937943
..      ...         ...        ...
361  tether  2026-03-09  91.938666
362  tether  2026-03-10  92.314270
363  tether  2026-03-11  91.976112
364  tether  2026-03-12  92.233824
365  tether  2026-03-12  92.340839

[366 rows x 3 columns]

### 3.2.4 Cobmining to Single Dataframe

In [54]:
df_top3_crypto = pd.concat([df_top3_crypto_bitcoin, df_top3_crypto_ethereum, df_top3_crypto_tether], axis=0, ignore_index=True)

In [55]:
df_top3_crypto

      coin_id        date         price
0     bitcoin  2025-03-13  7.311397e+06
1     bitcoin  2025-03-14  7.049332e+06
2     bitcoin  2025-03-15  7.301206e+06
3     bitcoin  2025-03-16  7.337203e+06
4     bitcoin  2025-03-17  7.182715e+06
...       ...         ...           ...
1093   tether  2026-03-09  9.193867e+01
1094   tether  2026-03-10  9.231427e+01
1095   tether  2026-03-11  9.197611e+01
1096   tether  2026-03-12  9.223382e+01
1097   tether  2026-03-12  9.234084e+01

[1098 rows x 3 columns]

In [56]:
df_top3_crypto.rename(columns={'price': 'price_inr'}, inplace=True)

In [57]:
df_top3_crypto.columns = df_top3_crypto.columns.str.upper()

In [58]:
df_top3_crypto.to_csv("data_top3.csv",index = False)

## 3.3 Oil Prices

In [59]:
df_oil

             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10109  2026-03-03  74.48
10110  2026-03-04  74.58
10111  2026-03-05  80.88
10112  2026-03-06  90.77
10113  2026-03-09  94.65

[10114 rows x 2 columns]

In [60]:
df_oil.columns = df_oil.columns.str.upper()

In [61]:
df_oil = df_oil[
    (df_oil['DATE'] >= '2020-01-01') &
    (df_oil['DATE'] <= '2026-01-31')
]

In [62]:
df_oil.rename(columns={'PRICE': 'PRICE_INR'}, inplace=True)

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_81765/2270245339.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_oil.rename(columns={'PRICE': 'PRICE_INR'}, inplace=True)

## 3.4 yfinance Stocks

In [63]:
df_stocks

Price             Close                                     High  \
Ticker            ^GSPC         ^IXIC         ^NSEI        ^GSPC
Date
2020-01-01          NaN           NaN  12182.500000          NaN
2020-01-02  3257.850098   9092.190430  12282.200195  3258.139893
2020-01-03  3234.850098   9020.769531  12226.650391  3246.149902
2020-01-06  3246.280029   9071.469727  11993.049805  3246.840088
2020-01-07  3237.179932   9068.580078  12052.950195  3244.909912
...                 ...           ...           ...          ...
2025-09-23  6656.919922  22573.470703  25169.500000  6699.520020
2025-09-24  6637.970215  22497.859375  25056.900391  6672.660156
2025-09-25  6604.720215  22384.699219  24890.849609  6619.000000
2025-09-26  6643.700195  22484.070312  24654.699219  6648.970215
2025-09-29  6661.209961  22591.150391  24634.900391  6677.310059

Price                                           Low                \
Ticker             ^IXIC         ^NSEI        ^GSPC         ^IXIC
Date
2020-01-01           NaN  12222.200195          NaN           NaN
2020-01-02   9093.429688  12289.900391  3235.530029   9010.889648
2020-01-03   9065.759766  12265.599609  3222.340088   8976.429688
2020-01-06   9072.410156  12179.099609  3214.639893   8943.500000
2020-01-07   9091.929688  12152.150391  3232.429932   9042.549805
...                  ...           ...          ...           ...
2025-09-23  22785.130859  25261.900391  6645.580078  22539.039062
2025-09-24  22657.449219  25149.849609  6621.759766  22397.000000
2025-09-25  22456.779297  25092.699219  6569.220215  22185.869141
2025-09-26  22488.179688  24868.599609  6604.430176  22285.439453
2025-09-29  22704.900391  24791.300781  6644.490234  22536.050781

Price                            Open                              \
Ticker             ^NSEI        ^GSPC         ^IXIC         ^NSEI
Date
2020-01-01  12165.299805          NaN           NaN  12202.150391
2020-01-02  12195.250000  3244.669922   9039.459961  12198.549805
2020-01-03  12191.349609  3226.360107   8976.429688  12261.099609
2020-01-06  11974.200195  3217.550049   8943.500000  12170.599609
2020-01-07  12005.349609  3241.860107   9076.639648  12079.099609
...                  ...          ...           ...           ...
2025-09-23  25084.650391  6692.439941  22782.720703  25209.000000
2025-09-24  25027.449219  6669.790039  22656.019531  25108.750000
2025-09-25  24878.300781  6608.189941  22318.769531  25034.500000
2025-09-26  24629.449219  6615.379883  22403.269531  24818.550781
2025-09-29  24606.199219  6661.580078  22605.300781  24728.550781

Price             Volume
Ticker             ^GSPC         ^IXIC     ^NSEI
Date
2020-01-01           NaN           NaN  304100.0
2020-01-02  3.459930e+09  2.862700e+09  407700.0
2020-01-03  3.484700e+09  2.586520e+09  428800.0
2020-01-06  3.702460e+09  2.810450e+09  396500.0
2020-01-07  3.435910e+09  2.381740e+09  447800.0
...                  ...           ...       ...
2025-09-23  5.633620e+09  9.822620e+09  299200.0
2025-09-24  5.459180e+09  9.184030e+09  244400.0
2025-09-25  5.874670e+09  9.960330e+09  342500.0
2025-09-26  5.103110e+09  8.488400e+09  291500.0
2025-09-29  5.358760e+09  9.046720e+09  394400.0

[1490 rows x 15 columns]

In [64]:
df_stocks= (
    df_stocks
    .stack(level='Ticker')
    .reset_index()
    .rename(columns={'Ticker': 'ticker'})
)

/var/folders/_x/xjprn7fn01v4sclwmkr7t81c0000gn/T/ipykernel_81765/2203892245.py:3: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  .stack(level='Ticker')

In [65]:
numeric_cols = ['Open', 'High', 'Low', 'Close', 'Volume']

df_stocks[numeric_cols] = df_stocks.groupby('ticker')[numeric_cols].transform(
    lambda x: x.fillna(x.mean())
)

In [66]:
df_stocks.columns = df_stocks.columns.str.upper()

In [67]:
df_stocks['TICKER'] = df_stocks['TICKER'].str.replace('^', '', regex=False)

In [68]:
df_stocks = df_stocks[['DATE', 'OPEN', 'HIGH', 'LOW', 'CLOSE', 'VOLUME', 'TICKER']]

# 4. Data to SQL

## 4.1 Creating Connection

In [70]:
conn = ps.connect(
    host = "localhost",
    user = "root",
    password= "Mano_rootsql0481",
    database= "cross_market_analysis"
)

In [71]:
cursor = conn.cursor()

## 4.2 Designing Database Tables

### 4.2.1 Table: CRYPTOCURRENCIES

In [73]:
cursor.execute("CREATE TABLE IF NOT EXISTS CRYPTOCURRENCIES (ID VARCHAR(100) PRIMARY KEY, SYMBOL VARCHAR(100), NAME VARCHAR(100), CURRENT_PRICE DECIMAL(30,6), MARKET_CAP BIGINT, MARKET_CAP_RANK INT, TOTAL_VOLUME BIGINT, CIRCULATING_SUPPLY DECIMAL(30,6), TOTAL_SUPPLY DECIMAL(30,6), ATH DECIMAL(30,6), ATL DECIMAL(30,6), LAST_UPDATED DATE)")

0

In [74]:
cursor.execute(
    """
    CREATE TABLE IF NOT EXISTS CRYPTO_PRICES(
    COIN_ID VARCHAR(50) REFERENCES CRYPTOCURRENCIES (ID),
    DATE DATE,
    PRICE_INR DECIMAL(30, 6)
    )
    """
    )

0

In [75]:
cursor.execute(
    """
    CREATE TABLE IF NOT EXISTS OIL_PRICES(
    DATE DATE PRIMARY KEY,
    PRICE_INR DECIMAL(18,6)
    )
    """
    )

0

In [76]:
cursor.execute(
    """
    CREATE TABLE IF NOT EXISTS STOCK_PRICES(
    DATE DATE,
    OPEN DECIMAL(18,6),
    HIGH DECIMAL(18,6),
    LOW DECIMAL(18,6),
    CLOSE DECIMAL(18,6),
    VOLUME BIGINT,
    TICKER VARCHAR(20)
    )
    """
)

0

## 4.3 Pushing Data to SQL

### 4.3.1 Creating Engine

In [77]:
engine = ce(
    f"mysql+pymysql://root:Mano_rootsql0481@localhost:3306/cross_market_analysis",
    echo = False
)

In [79]:
df_crypto.to_sql(
    'CRYPTOCURRENCIES',
    con=engine,
    if_exists='append',
    index=False
)

750

In [80]:
df_top3_crypto.to_sql(
    'CRYPTO_PRICES',
    con=engine,
    if_exists='append',
    index=False
)

1098

In [81]:
df_oil.to_sql(
    'OIL_PRICES',
    con=engine,
    if_exists='append',
    index=False
)

1520

In [82]:
df_stocks.to_sql(
    'STOCK_PRICES',
    con=engine,
    if_exists='append',
    index=False
)

4309